### ISSUE TITLE
Lcov report potentially wrong

### ISSUE THREAD

**Issue by ffMathy** [SteveGilham/altcover#100]
After every `end_of_record`, I think there should be a `TN:`.

The Coverage Gutters extension does not understand the Lcov file if there isn't, and I'm not sure if it's a bug in AltCover, or if it's a bug in Coverage Gutters.

See https://github.com/ryanluker/vscode-coverage-gutters/issues/279

**Comment by SteveGilham** [comment]
Yes, despite the `geninfo(1)` man page defining the format saying
```
A tracefile is made up of several human-readable lines of text, divided into sections. If available, a tracefile begins with the testname which is stored in the following format:

TN:<test name>

For each source file referenced in the .da file, there is a section containing filename and coverage data:

SF:<absolute path to the source file>

Following is a list of line numbers for each function name found in the source file:

FN:<line number of function start>,<function name>
...
```
it seems (from the one example file I've found online) that a more accurate description would be
```
A tracefile is made up of several human-readable lines of text, divided into sections.

For each source file referenced in the .da file, there is a section containing testname:

TN:<test name>

the filename:

SF:<absolute path to the source file>

and coverage data, beginning with a list of line numbers for each function name found in the source file:

FN:<line number of function start>,<function name>
...
```

The build failure in the PR was due to the `writer.WriteLine "TN:"` being now only present in the NCover format braqnch of the match expression, and not in the "everything else" (OpenCover) branch.  Duplicating the line there fixes the build.

**Comment by SteveGilham** [comment]
Assuming that the current [AppVeyor build 7.1.794](https://ci.appveyor.com/project/SteveGilham/altcover/history) completes, [the build artifacts](https://ci.appveyor.com/project/SteveGilham/altcover/builds/36189495/artifacts) will contain suitable `.nupkg` files for testing the fixes to issues #98 (substituting in the listed $() expressions), #99, and this one.

**Comment by ffMathy** [comment]
Wow that's perfect! Thank you!

**Comment by SteveGilham** [comment]
The fix to emit a per-file `TN:` line is in the [7.1.795 release](https://www.nuget.org/packages/AltCover/7.1.795). Is there anything else needed to resolve this issue?
