### ISSUE TITLE
Multiple test assemblies in one run(.sln) with defined output path overwriting coverage.xml results

### ISSUE THREAD

**Issue by andreas-marccain** [SteveGilham/altcover#103]
Hi,

how to setup an path for AltcoverXmlReport when runing dotnet test for a solution with multiple test assemblies.

We are using "dotnet test" with an .sln file as input. 
The solution contains multiple test assemblies.
 
In our ci pipeline we want the test result to be present in an temp folder outside the source code. Setting the switch /p:AltCoverXmlReport=/_temp/coverage.xml all test runs will override this file and only the coverage of the last test assembly is kept.

Is there a way to achieve this?

**Comment by SteveGilham** [comment]
With the latest release, v7.1.795, if you include the literal `$(ProjectName)` in the report file path, then that will be explicitly replaced, in the circumstances that MSBuild hasn't done so already, so, for example
```
`/p:AltCoverXmlReport=/_temp/$(ProjectName).coverage.xml
```
will drop a set of distinctly named files into the temporary folder.

**Comment by andreas-marccain** [comment]
Hi, 

thanks for your fast feedback. Updating to the mentioned version and changing the path works.

We are using 

> AltCoverXmlReport="$(Agent.TempDirectory)/$(ProjectName)/coverage.xml"

in Azure DevOps where the first $(var) is replaced by the pipeline and the second one by altcover.
