### ISSUE TITLE
Dynamically excluding third party assemblies

### ISSUE THREAD

**Issue by ffMathy** [SteveGilham/altcover#108]
When I run AltCover, it generates coverage for all assemblies, including assemblies that are not my project.

I get that this makes sense from an implementation stand-point, and I am aware that there exists filters that can exclude assemblies, and that people can just use that.

However, in my use-case, I am building a test-runner CLI, which doesn't have the information about what assemblies to include/exclude.

So let's say my user uses the CLI to run his tests, using `pruner run`.

The user has 4 projects:
- Foo.Application
- Foo.Domain
- Foo.Application.Tests
- Foo.Domain.Tests

Each of these assemblies reference NuGet dependencies like `System.Linq.Async` or `Newtonsoft.Json`.

What I would like to be able to do somehow (but dynamically, not explicitly), is to only instrument assemblies that I own. In other words, instrumenting the 4 assemblies above, excluding the NuGet dependencies.

Can we find a way to solve this somehow?

It's hard to describe my problem. I hope it makes sense somehow.

**Comment by ffMathy** [comment]
Oh, and I know I just had another issue open. If you'd like a break from all this chaos and focus on your own things, I completely understand. I feel like I'm constantly hogging your resources and energy, and I'm sorry for that.

I love the library though, and I think I'll keep reporting stuff until I am 100% happy. I think this must be one of the last issues I have with the library, and it's more of a missing feature really than a so-called "issue".

**Comment by ffMathy** [comment]
Perhaps the DataCollector could somehow help out?

**Comment by ffMathy** [comment]
And to emphasize: I am aware of `AltCoverAssemblyFilter` and `AltCoverAssemblyExcludeFilter`. The dilemma is that I can't know at runtime what my user's assembly names of interest are, and I realize that also makes it hard for AltCover to detect it.

It's an interesting challenge with a huge reward though. I think other coverage tools must do somewhat the same?

**Comment by SteveGilham** [comment]
`OpenCover` (and at least the original `NCover`), which use the .net Framework profiling APIs instrument everything loaded into process that has a matching .pdb file, unless deliberately excluded at the command line.  Not sure about `minicover`, but `coverlet` instruments the dependencies of the test file built by the project, again, unless excluded.

AltCover has `/p:AltCoverLocalSource=true` to ignore assemblies with .pdbs that don’t refer to source files located on the machine currently running, which should do what you need when build and test are on the same machine.  If that's not the case, some heuristic on last-modified date would be a possible approach.

**Comment by ffMathy** [comment]
Ah - that worked! Thank you once again Steve! :pray:
