### ISSUE TITLE
problem loading files that are copied to output directory

### ISSUE THREAD

**Issue by dhuyvett** [SteveGilham/altcover#112]
I have a test project that copies some files to the output directory

    <ItemGroup>
        <None Update="DocStore\Foo.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="DocStore\Bar.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

and the test loads the files 

    var filePath = Path.Combine("DocStore", $"{key}.json");
    var fileContents = await File.ReadAllTextAsync(filePath);

This all works fine with AltCover 7.3.802

but with AltCover 7.3.806 I get:

    System.IO.DirectoryNotFoundException : Could not find a part of the path '/home/user/source/MyProject/MyProject.Test/bin/Release/netcoreapp3.1/__Instrumented_MyProject.Test/DocStore/Foo.json'.

Sure enough, after the build, that file doesn't exist.  it is: '/home/user/source/MyProject/MyProject.Test/bin/Release/netcoreapp3.1/DocStore/Foo.json

I am running this with:

```bash
$ dotnet restore
$ dotnet build --no-restore -c Release -p:Version="1.0.1"
$ dotnet test MyProject.Test --no-restore --no-build -c Release /p:AltCover="true" /p:AltCoverxmlReport="/tmp/testReports/MyProject.xml" /p:AltCoverAssemblyExcludeFilter="MyProject.Test"
```

**Comment by SteveGilham** [comment]
This comes from the change in build 805 to stop copying the files in the output directory three times and only do it once, in the process moving the test execution directory from the output directory to a different, temporary, directory.

These .json files are not copied to the output directory itself (whence they would be copied), but instead to a sub-directory thereof, and that directory remains untouched, so the relative path look-up is naturally failing.

**Comment by ffMathy** [comment]
Can AltCover perhaps copy the needed files over that are flagged as "Copy to output directory"?

**Comment by SteveGilham** [comment]
Two alternative approaches in the  [v7.4.807](https://www.nuget.org/packages/AltCover/7.4.807) release -- now `<None>` items in sub-folders are now also copied by default; or the tests can be done opting back into the previous in-place behaviour via  `/p:AltCoverInPlace=true`.

**NB** `/p:AltCoverInPlace=true` will not play well with the concurrent instrument-and-test behaviour of `dotnet test [multipletestprojects].sln /p:AltCover="true" --output [commonArtifactsFolder]`

**Comment by ffMathy** [comment]
Isn't it possible to just make it respect this property instead?

![image](https://user-images.githubusercontent.com/2824010/104312850-799d8400-54d7-11eb-9605-015b29788128.png)

Isn't uploading all `None` items too much - these aren't copied by Visual Studio itself either. Only if the `CopyToOutputDirectory` part is set.

**Comment by SteveGilham** [comment]
Elaborating, as per the release notes

  * If `/p:AltCoverInPlace` is not `true`, then copy all files in the project included as `<None Include="./[some subdirectory]/..."` with `CopyToOutputDirectory` of `Always` or `PreserveNewest` to the appropriate relative location wrt the intrumented files

**Comment by ffMathy** [comment]
Ah - perfect! My bad! 🙏
