### ISSUE TITLE
Getting intermediate (current) coverage percent during tests execution

### ISSUE THREAD

**Issue by IgorBuchelnikov** [SteveGilham/altcover#114]
Is there a way? I need it for generating code of tests.
I mean the opportunity to get a coverage percent within the test code (C#) during it is executed.

**Comment by SteveGilham** [comment]
At the moment, the nearest approach would involve using the recording pause/resume facility, combined with then suspending the test processing, to get intermediate results -- probably not a practical approach outside of an operational test context.

The information is there implicitly; the problem lies in how to actually communicate that information out from the recorder assembly at the bottom of the test stack.  That I don't have a good solution for.

**Comment by IgorBuchelnikov** [comment]
My problem is that my test method takes 4 hours. It combines many variants of input data. I want to get only useful variants, that increase coverage to minimize the time of unit test execution.

**Comment by SteveGilham** [comment]
Some requirements gathering here

How are you running the tests with coverage?  Under `dotnet test`? Classic `NUnit` (or equivalent) on a set of instrumented files? Something else?

What format for the test progress data would be of use?  An update after every test case?  An update every N visits?  To console? To file? To some other data sink (e.g. Debug.Write)?  As a percentage or as number of distinct visited locations?

**Comment by IgorBuchelnikov** [comment]
Here is my project https://github.com/IgorBuchelnikov/ObservableComputations
I use `NUnit `and `dotnet test`. A number of distinct visited locations would be excellent.  A percentage is also acceptable. 
I expect to write something like this:

```
[Test]
public void TestMethod()
{
    int lastDistinctVisitedLocationsCount = 0;
	
    for (int i = 0, i < 10000; i++)
            for (int j = 0, j < 10000; j++)  
            {
				test(i, j);
				
				int currentDistinctVisitedLocationsCount = 
				    AltCoverApi.GetCurrentDistinctVisitedLocationsCount("ObservableComputations");
					
				if (currentDistinctVisitedLocationsCount > lastDistinctVisitedLocationsCount)
				{
					File.AppendLines("UsefulCombinations.txt", new []{$"{i} {j}"});
					lastDistinctVisitedLocationsCount = currentDistinctVisitedLocationsCount;
				}
            }
}
```

**Comment by SteveGilham** [comment]
An interesting concept.  I shall have to think on this one.

**Comment by SteveGilham** [comment]
In hew release [v7.5.809](https://www.nuget.org/packages/AltCover/7.5.809), there's an [AltCover.Monitor API](https://stevegilham.github.io/altcover/AltCover.Monitor/AltCover.Monitor-apidoc) that should address the problem.

**Comment by SteveGilham** [comment]
The equivalent to your code fragment would be
```
[Test]
public void TestMethod()
{
    int lastDistinctVisitedLocationsCount = 0;
	
    for (int i = 0, i < 10000; i++)
            for (int j = 0, j < 10000; j++)  
            {
		test(i, j);
				
		if(AltCover.Monitor.TryGetVisitTotals(out totals))
        {
            if (out.Code > lastDistinctVisitedLocationsCount)
            {
                File.AppendLines("UsefulCombinations.txt", new []{$"{i} {j}"});
                lastDistinctVisitedLocationsCount = out.Code;
            }
        }
    }
}
```

**Comment by IgorBuchelnikov** [comment]
Thanks a lot! Did not expect the problem to be resolved so quickly. I'll try it next week

**Comment by ffMathy** [comment]
Is there a way to observe coverage as the tests run, from a different process?

Pruner could be interested in this, so that coverage could be updated more often.

**Comment by SteveGilham** [comment]
That would be a little more complicated than simply invoking recorder APIs in-process.  It might take a little longer...

**Comment by ffMathy** [comment]
It's a highly optional nice-to-have feature. I was just inspired when I saw the release notes :smirk:

The use-case is that when running `dotnet test` on solution-level, it might be useful to see updated coverage on-the-fly, instead of when all tests of all projects have been run.

**Comment by SteveGilham** [comment]
For that extension, a project level granularity could be achieved by applying a FileSystemWatcher to the reports folder for new and modified files, looking at the top level `<Summary ... /> records, getting an accumulation of coverable and covered code points.

**Comment by ffMathy** [comment]
Yes, that would certainly help make the granularity project-level instead of solution-level, but it would be even cooler if it was on a test-level (every time a test ran).

But I honestly think it's not worth it. Exposing such functionality is probably difficult and not worth it, considering I'll probably be the only one ever using it.

And the reward is even small as well.

**Comment by IgorBuchelnikov** [comment]
I tried to use AltCover.Monitor. 2 issues:

1) I had to add the reference to AltCover.Monitor.dll assembly in my testing project myself (ObesrvableComputations.Test). altcover package didn't.

2) My tested assembly (ObesrvableComputations) has internal methods (ValidateConsistency()) that are visible ([InternalsVisibleTo attribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-5.0)) to the testing assembly (ObesrvableComputations.Test). When I run
`dotnet test --filter Name~ThenOrdering /p:AltCover=true `
I get:
```
----> System.MethodAccessException : Attempt by method 'ObservableComputations.Test.ThenOrderingOrderingTests.test(Int32[], Int32[], Int32[], System.ComponentModel.ListSortDirection, System.ComponentModel.ListSortDirection)' to access method 'ObservableComputations.ThenOrdering`2<System.__Canon,System.Nullable`1<System.Int32>>.ValidateConsistency()' failed.
```

When I run
`dotnet test --filter Name~ThenOrdering `
There is no error.

**Comment by SteveGilham** [comment]
1) At the moment, you need the altcover.api package for this, which places the assemblies where the linker wants them

2) If your assembly is strong-named, then this would be expected -- the instrumentation behaviour rewrites the assembly, so you'll need to use `/p:AltCoverStrongNameKey`  to indicate a key to use to re-apply the signature.

**Comment by IgorBuchelnikov** [comment]
Now it works. Thanks again!
