### ISSUE TITLE
Monitor.TryGetVisitTotals: System.InvalidOperationException: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by IgorBuchelnikov** [SteveGilham/altcover#117]
Exception while executing AltCover.Monitor.TryGetVisitTotals(out PointCount pointCount)
Likely a race condition.
There is no log file.

Call stack trace:
```
   System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   AltCover.Monitor.<>c.<TryGetVisitTotals>b__4_2(PointCount t, Type i)
   System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   AltCover.Monitor.TryGetVisitTotals(PointCount& totals)
```

**Comment by SteveGilham** [comment]
That's interesting, as there's explicitly a lock around the access.  This may take some time tracking down.

**Comment by IgorBuchelnikov** [comment]
This error is very rare. I ran unit tests this night. TryGetVisitTotals was called very, very many times (~1000000) and without errors

**Comment by SteveGilham** [comment]
In the new [v7.6.812 release](https://www.nuget.org/packages/AltCover/7.6.812), I've re-implemented this API so that it doesn't need to examine collections that may change while they're being examined.
