### ISSUE TITLE
After migration to .NET5 tests using files with Content/ CopyToOutputDirectory are failing

### ISSUE THREAD

**Issue by dalibor-sanzeru** [SteveGilham/altcover#126]
```
 dotnet.exe test --configuration "Debug" pass with result: 
 Passed!  - Failed:     0, Passed:   814, Skipped:     0, Total:   814, Duration: 15 s - PredavamApi.Tests.dll (net5.0)
```

But when running with /p:AltCover=true  tests are failing as they cannot find CopyToOutputDirectory files. (html templates in this case).

```
dotnet.exe test --configuration "Debug" /p:AltCover=true /p:AltCoverLocalSource=true

  Error Message:
   System.IO.DirectoryNotFoundException : Could not find a part of the path '**C:\Workspace\Vyrabam\PredavamApi.Tests\bin\Debug\net5.0\__Instrumented_PredavamApi.Tests\Mailing\Templates\HtmlEmailTemplate.html**'.
  Stack Trace:
     at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at PredavamApi.Mailing.MailGeneratorService.CreateEmailBody[TData](TData data, Boolean showFooterData) in C:\Workspace\Vyrabam\PredavamApi\Mailing\MailGeneratorService.cs:line 122
   at PredavamApi.Tests.Mailing.MailGeneratorServiceTest.CreateEmailBody_PreMailerCalled_InlineHtmlIGenerated() in C:\Workspace\Vyrabam\PredavamApi.Tests\Mailing\MailGeneratorServiceTest.cs:line 167
  Failed CreateEmailBody_SuccessRegistration_FieldsFilledIn [1 ms]
```

Sorry if this is not directly related to altcover, but it worked before switch into .net5, so its difficult to say if this is .net5, altcover or combination of both related.

Questions also is -> if copytooutputfolder/always files are taken from correct location and if altcover support this use-case.

Thanks for help & ideas.

**Comment by SteveGilham** [comment]
From that error report, the `**` at the start and end of the path in the exception message look suspicious to me when compared with a trivial example of reading a non-existent file path

![image](https://user-images.githubusercontent.com/7460854/115224464-c7441100-a104-11eb-9857-ff6947a81c32.png)

For AltCover v7.4.808 or later all `<Content>`  files -- and indeed any other sort that honours `<CopyToOutputDirectory>` -- should be copied to the appropriate relative directory; that's something that can be checked by simply looking at the `__Instrumented_$(ProjectName)` directory and sub-directories.

**Comment by dalibor-sanzeru** [comment]
Hi Steve,
This ** were added by copy-pasting from powershell here into github. Sorry for copy-typo.

For clean view I am attaching it here again:
```

Error Message:
   System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Workspace\Vyrabam\PredavamApi.Tests\bin\Debug\net5.0\__Instrumented_PredavamApi.Tests\Mailing\Templates\HtmlEmailTemplate.html'.
  Stack Trace:
     at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at PredavamApi.Mailing.MailGeneratorService.CreateEmailBody[TData](TData data, Boolean showFooterData) in C:\Workspace\Vyrabam\PredavamApi\Mailing\MailGeneratorService.cs:line 122
   at PredavamApi.Tests.Mailing.MailGeneratorServiceTest.CreateEmailBody_SuccessRegistration_FieldsFilledIn() in C:\Workspace\Vyrabam\PredavamApi.Tests\Mailing\MailGeneratorServiceTest.cs:line 41
```

I've checked folder you mentioned yet before -> but directory 'Mailing/Templates/' and files are really not copyed to Instrumented folder, they are only part of bin folder.

From laic perspective it looks to me like 'standard' dotnet test command is running in context of bin folder.
But mentioned altcover command is running in context of InstrumentedFolder - where files are not copyed.

This instrumenation folder is thing of altcover or some dependency? 
I haven't found much sources about it - thats reason I am quessing if something has changed in net5 vs .net alcover implementation.

Screens with bin folder and Instrumetation folder attached (sorted by type - no folders inside Instrumentation folder).

Maybe switch? /p:AltCoverLocalSource=true
Thanks for brainstorming...  

![image](https://user-images.githubusercontent.com/19836016/115617136-501fa000-a2f1-11eb-9442-7504e015c205.png)

![image](https://user-images.githubusercontent.com/19836016/115617333-9412a500-a2f1-11eb-9186-7aceb1c16fde.png)

**Comment by SteveGilham** [comment]
The `__Instrumented_...` folder is part of the AltCover process; AltCover works by rewriting the assemblies of interest, to inject the code needed to record each visit, with the test then being run over the rewritten code, leaving the as-built assemblies untouched.

For `dotnet test`, by default, everything in the project output directory (MSBuild's `$(TargetDir)`) is copied or (for assemblies that are being instrumented for coverage) rewritten to `$(TargetDir)/__Instrumented_$(ProjectName)`; and the `VSTestTask` operation run in the context of that directory.  

Before the tests are run though, the AltCover  targets file performs a copy operation for all files with `CopyToOutputDirectory` of `Always` or `Copy if newer`; this copy operation was added as part of the fix for issue #112 (concerning files copied relative to the output directory exactly as here), and is tested as part of the AltCover build process.  The copy process does assume that the files are specified by relative directory e.g.
```
    <Content Include="Data\Deeper\Bar.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```
which specifies a file at `$(ProjectDir)\Data\Deeper\Bar.txt` which is then copied to `$(TargetDir)\Data\Deeper\Bar.txt` as part of the build, and the copied again from that location to `$(TargetDir)\__Instrumented_$(ProjectName)\Data\Deeper\Bar.txt` by the AltCover process.

How precisely are the files of interest here specified in your project file? (i.e. has that changed/been changed for you by one or other parts of the build process with the move to .net 5.0?)

There is an option `/p:AltCoverInPlace=true` which instead copies all files from `$(TargetDir)` to `$(TargetDir)/__Saved_$(AltCoverInstrumentedDirectory)_$(ProjectName)`, and then rewrites from there into `$(TargetDir)`; tests are then run from that directory, and finally, the original files are copied back; this does not mix well with cases where tests are run like `dotnet test [multipletestprojects].sln /p:AltCover="true" --output [commonArtifactsFolder]`, but may serve as a work-round.

**Comment by SteveGilham** [comment]
In the meantime, while waiting to find out about the file specifications, I've made a speculative change that may possibly address the issue
[altcover.8.2.284-github-pre.nupkg.zip](https://github.com/SteveGilham/altcover/files/6372701/altcover.8.2.284-github-pre.nupkg.zip)

If you could try it out, it would be useful, so I can see whether it is worth exploring further.

This build also contains a fix for issue #125 (fixing an oversight in the cyclomatic complexity algorithm).

**Comment by dalibor-sanzeru** [comment]
Hi Steve,
I've checked that pre-released nuget and all tests are running now. Great!

**THANK YOU.**

I am attaching API csproj as you asked - for confirmation:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Mailing\Templates\bootstrap.min.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\CreateInvoice.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\DoPaymentBuyer.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\DoRating.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\HasUnreadMessage.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\ResetPassword.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\SubscribeRequested.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\SuccessRegistration.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\ConfirmRegistration.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\HtmlEmailTemplate.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\OrderCreatedForSeller.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\OrderCreatedForBuyer.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Mailing\Templates\OrderStateChangedSeller.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="9.5.4" />
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.51.0.2294" />
    <PackageReference Include="Handlebars.Net" Version="2.0.7" />
    <PackageReference Include="Haukcode.DinkToPdf" Version="1.1.2" />
    <PackageReference Include="IbanNet.FluentValidation" Version="4.3.0" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="7.23.3" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="5.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
    <PackageReference Include="MimeDetective.InMemory" Version="0.2.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.2.0" />
    <PackageReference Include="PreMailer.Net" Version="2.2.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="4.1.0" />
    <PackageReference Include="Serilog.Enrichers.AspNetCore.HttpContext" Version="1.0.1" />
    <PackageReference Include="Serilog.Enrichers.Memory" Version="1.0.4" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
    <PackageReference Include="WebPush" Version="1.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PredavamApi.Common\PredavamApi.Common.csproj" />
    <ProjectReference Include="..\PredavamApi.DataSeed\PredavamApi.DataSeed.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Chat\Messages\" />
    <Folder Include="Claims\Repository\" />
    <Folder Include="ExternalServices\Models\" />
    <Folder Include="Files\" />
    <Folder Include="logs\" />
  </ItemGroup>
</Project>

```

**Comment by SteveGilham** [comment]
Now packaged as release [v8.2.820](https://www.nuget.org/packages/altcover/8.2.820).
