### ISSUE TITLE
Instructions for installing AltCover CLI

### ISSUE THREAD

**Issue by dustin-sier** [SteveGilham/altcover#129]
I've been reading through the documentation as much as possible, but can find no where that mentions how to install AltCover CLI for use.

If possible, installation instructions and a quick walkthrough of using it with mono would be good. Hopefully its just me missing it in the documentation.

**Comment by dustin-sier** [comment]
I answered my own question by being reminded that dotnet tool exists. Here's the Hanelman article that helped: https://www.hanselman.com/blog/altcover-and-reportgenerator-give-amazing-code-coverage-on-net-core

**Comment by SteveGilham** [comment]
In any case, prompted by this, I've [added instructions to the FAQ](https://github.com/SteveGilham/altcover/wiki/FAQ#how-do-i-install-the-altcover-cli).
