### ISSUE TITLE
dotnet test /p:AltCover=true yields `error: --inputDirectory : ....` error

### ISSUE THREAD

**Issue by DejanPopovic1** [SteveGilham/altcover#137]
I have tried on both framework and core projects to run dotnet test :/pAltCover=true. However, I get a console error.

However I get an error: 
```
C:\Users\xxxxxxxxxx\.nuget\packages\altcover\8.2.835\build\netstandard2.0\AltCover.targets(83,5): error : --inputDirectory : Directory C:\directory\to\my\test\project\Project\ProjectTest\bin\Debug\netcoreapp2.1\ not found [C:\directory\to\my\test\project\Project\ProjectTest\ProjectTest.csproj]
```

No one has mentioned this issue which leads me to believe this isnt an issue but rather a user error. Could anyone advise?

**Comment by DejanPopovic1** [comment]
I tried setting up application code project and test project using visual studio **and** using the dotnet console CLI. Same result for both old version and new versions of framework and core

**Comment by DejanPopovic1** [comment]
Interesting, I created a new project with a very short project path, and it finally seems to work.

The problematic path length that I tried before had somewhere around 110 character

**Comment by SteveGilham** [comment]
I have [noticed elsewhere](https://stevegilham.blogspot.com/2021/10/f-and-opensilver-v10.html) that parts of the MSBuild process (at least the Copy task, likely more) still appear to labour under the old 255 character path limits from forever ago. If the project already has a long file path, some of the directory structure and files generated under that point can push over that limit.

**Comment by SteveGilham** [comment]
A quick experiment with long path names -- this one makes the as built assembly have a >255 character path name -- has shown a different error; a test project 
```
C:\Users\steve\Documents\GitHub\reproduce-altcover-error-master\reproduce-altcover-error-master\reproduce-altcover-error-master\reproduce-altcover-error-master\extended-repro-test-altcover-error-master\test-altcover-error-master.csproj
``` 
fails with 
```
Failed to launch testhost with error: System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Users\steve\Documents\GitHub\reproduce-altcover-error-master\reproduce-altcover-error-master\reproduce-altcover-error-master\reproduce-altcover-error-master\extended-repro-test-altcover-error-master\bin\Debug\net6.0\__Instrumented_test-altcover-error-master\testhost.exe' with working directory 'C:\Users\steve\Documents\GitHub\reproduce-altcover-error-master\reproduce-altcover-error-master\reproduce-altcover-error-master\reproduce-altcover-error-master\extended-repro-test-altcover-error-master\bin\Debug\net6.0\__Instrumented_test-altcover-error-master'. The directory name is invalid.)
```
and in this case, it's `System.Diagnostics.Process.Start()` that's unhappy.

My gut feel at this moment is that exactly which part of the process breaks is going to depend on the exact lengths of file and directory names, and hence which part of the process first spots a 256 character or longer path name that disagrees with it.

A work-round is to move the build artifacts from the test project(s) to somewhere at a shallower location in the directory tree, by specifying an explicit `OutputPath` property

**Comment by SteveGilham** [comment]
Taking this further, if the project path is long enough, even `dotnet build` fails -- a transient terminal window appears, and the process otherwise silently fails; 

The error originally reported comes from a simple `Directory.Exists`  check inside AltCover (the build output directory is implicitly added to the command, and the whole set of arguments go through the same validation as if in the command line tool), and that shows no problems with the long names I've been playing with; so the failure originally reported would indicate that the directory has indeed not been created.
