### ISSUE TITLE
The web service gets failed when the server is started to execute the test cases before collecting the coverage data.

### ISSUE THREAD

**Issue by tilak-nanavati-opshub** [SteveGilham/altcover#139]
To generate the code coverage we are following the steps given below:

**1. Install Altcover. (one-time step to be performed on machine where test instance will be deployed)
	a.	CMD> dotnet tool install --global altcover.global
2. Deploy the latest build of Web services.
3. Shut down the service and IIS.
4. Instrument the deployed binaries for the Services site.
	a.	CMD>altcover --save --inplace -i "[Path Prefix to DLLs]\bin"
5. Start the IIS and Services.**

After Step 5, we observe that the Service is not getting started with failure/error trace:
**Could not load file or assembly 'StackExchange.Redis.StrongName, Version=2.0.0.0
, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)**

We suspect that the Altcover is replacing the StackExchange.Redis assembly with a different version.

Can you pl help us with this issue? Any insights would be helpful.

PS: Adding environment-specific details.
**AltCover version: 8.2.835
.net framework version for project/service build: 4.7.2
.net framework version on deployed machine: 4.0**

**Comment by SteveGilham** [comment]
Sorry about the delay getting back to you -- been a busy week here.

> We suspect that the Altcover is replacing the StackExchange.Redis assembly with a different version.

That is correct.  Since it has not been excluded from instrumentation, that assembly will have been rewritten -- along with all other assemblies in the nominated directory -- to emit coverage data; and since no strong-name key has been supplied to the process, the rewrite will not be strong-named.

Presuming that you are not interested in how well you are covering third-party code like that, then add `-s "StackExchange\.Redis"` -- the `\` because these are regexes --  or some substring of `StackExchange\.Redis` that will not also exclude code you are interested in, to the command line.  The same goes for any other third-party assemblies in the target directory, in whose coverage you are not interested.

If you did want to get coverage data from that assembly you would need to have the original strong-naming `.snk` file and add it to the command line with the `-k` option to re-apply exact signing keys.

**Comment by tilak-nanavati-opshub** [comment]
Thank you for the detailed suggestion. We will try this and update here if it works.

**Comment by tilak-nanavati-opshub** [comment]
Hi Steve,

Our goal is to instrument only those DLLS which are of our interest and we must exclude the third-party jars out of the process.

Following DLLs we want to exclude:

_Microsoft.Web.RedisSessionStateProvider.dll
Pipelines.Sockets.Unofficial
Microsoft.WindowsAzure.Storage
Antlr3.Runtime
StackExchange.Redis_

We tried the following commands for the same -
**altcover --save --inplace -i "C:\inetpub\mr4devops-dailybuild\UI\bin" -fileFilter "StackExchange.Redis.*.dll|Antlr3.Runtime.*.dll|Microsoft.WindowsAzure.Storage.*.dll|Microsoft.Web.RedisSessionStateProvider.*.dll"**

**altcover --save --inplace -i "C:\inetpub\mr4devops-dailybuild\UI\bin" -fileFilter "StackExchange.Redis.*.dll|Pipeline.*.dll|Antlr3.Runtime.*.dll|Microsoft.WindowsAzure.Storage.*.dll|Microsoft.Web.RedisSessionStateProvider.*.dll"**

We also tried the negation for inclusion of specific dll over fileFilter with the below command:

**altcover --save --inplace -i "C:\inetpub\mr4devops-dailybuild\UI\bin" -fileFilter "^((?!Name.Web.UI).)*$"**

But none of the approaches essentially discards those unwanted DLLs. The DLLs meant to get excluded are still getting replaced in the service folder.

We need your help here to know if we are doing anything wrong.

**Comment by SteveGilham** [comment]
As listed in [the Usage guide](https://stevegilham.github.io/altcover/Usage), the `-f` (`--fileFilter`) option is for _source_ files to exclude from coverage (use case being for excluding generated code such as the designer code for UI), it's `-s` (`--assemblyFilter`) as noted above, to exclude assemblies.  [See also the relevant FAQ entry](https://github.com/SteveGilham/altcover/wiki/FAQ#how-do-i-exclude-an-assembly-from-coverage).

If you want simply to include all assemblies `ProductName.Web.UI.*`, then the simpler option is to use the shortcut
```
--assemblyFilter "?ProductName\.Web\.UI"
```
[See also the relevant FAQ entry](https://github.com/SteveGilham/altcover/wiki/FAQ#my-system-under-test-drags-in-a-large-number-of-other-assemblies-so-im-having-to-use-a-whole-bunch-of-filter-exclusions--is-there-a-way-to-just-opt-in-an-assembly-to-instrument).

**Comment by tilak-nanavati-opshub** [comment]
Thank you so much for quick turn around Steve, much appreciated. We will try this and post the update here.

**Comment by tilak-nanavati-opshub** [comment]
Hi Steve, 
By using **_--assemblyFilter_** fulfilled our purpose. We could generate the coverage of specific DLLs (using both inclusion and exclusion regex) worked for us.
Thank you.

**Comment by SteveGilham** [comment]
Glad to be of service
