### ISSUE TITLE
Will it run on .NET 4.8 and .NET 4.8.1?

### ISSUE THREAD

**Issue by kabua** [SteveGilham/altcover#186]
We are currently still using .NET 4.8 (and .NET 4.8.1) but are in the process of porting to .NET 7.  But in the meantime, we still need something that works for us today. Therefore, will Altcover work on these two framework versions?

On nuget.org, the framework tab states yes. However, the readme states only up to .NET 4.7.2

**Comment by SteveGilham** [comment]
Yes, it will.  The .NET framework is forward compatible - the net472 executables will run under later framework versions (and indeed do so on my own development machines).  That version is chosen as the Framework target purely for being  the oldest version still in support.

In the interests of backwards compatibility, the recorder assembly that actually commits coverage events to file is in fact built against NET 2.0, and that functions quite happily on later framework versions as well as on dotnet (up to the current 8.0 previews).

Similarly, the API builds targeting netstandard2.0 simply declare that they are using what is in fact a subset of the NET Framework 4.7.2 API surface, with an implicit "or later".
