### ISSUE TITLE
How to combine different coverage files?

### ISSUE THREAD

**Issue by 64J0** [SteveGilham/altcover#190]
## Description:

Hello, hope you're good.

I have some tests that run in parallel, and each is responsible for testing a module of the system. I'd like to combine all their coverage files (`.xml`) into a final single file.

Is it possible when using altcover? If it is, how?

**Comment by SteveGilham** [comment]
The `[Merge-OpenCover](https://stevegilham.com/altcover/PowerShell-integration#merge-opencover)` cmdlet can do this for you in a general case.

If the tests are being run on the exact same set of binaries, it is possible to do

1. instrument pmce
2. test 1
3. collect
4. test 2
5. collect
6. test 3
7. collect
8. ...

**Comment by 64J0** [comment]
They run in parallel in different virtual machines, but indeed, they are related to the same binaries. Thanks for the fast reply @SteveGilham.

**Comment by 64J0** [comment]
Possibly related: https://stackoverflow.com/questions/23089627/opencover-possible-to-merge-multiple-reports-into-one.

I'm going to start implementing/testing this tomorrow.

**Comment by 64J0** [comment]
I'm reopening this issue since I noticed that this tool documentation is for PowerShell. Does it work in Linux shell as well (like bash, for example)?

**Comment by 64J0** [comment]
Apparently PowerShell works on Linux -> https://learn.microsoft.com/pt-br/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.3

**Comment by 64J0** [comment]
To present an overview of what I'm trying:

- [ ] [Install](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.3) and start (`pwsh`) PowerShell on Linux
- [ ] Install AltCover as a global tool (`dotnet tool install --global altcover.global --version 8.6.68`)
- [ ] Use the ImportModule command with `altcover ImportModule`

But, whenever I try to use the `Merge-OpenCover` command it throws this error:

```bash
Merge-OpenCover: The term 'Merge-OpenCover' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by 64J0** [comment]
Actually, I understood how to use it now, after checking this file: 

* https://github.com/SteveGilham/altcover/blob/2afb2c0102c99b5c5d00be7119c5be9a09dbb984/Build/merge-coverage.ps1
