### ISSUE TITLE
Running AltCover Runner in parallel mode

### ISSUE THREAD

**Issue by headshog** [SteveGilham/altcover#212]
Hi! Im trying to collect code coverage from a bunch of input files in parallel mode (instrumenting code with AltCover and then launching several AltCover Runner processes). But there is a problem with shared report file (which is specified by ActCover --report option). Runner says: `The process cannot access the file '/coverage/coverage.xml' because it is being used by another process.`.

My question is: is it possible to run AltCover Runner without opening this shared coverage file, or is there any way to collect coverage using AltCover in parallel mode?

**Comment by SteveGilham** [comment]
Parallel testing can be done via the command-line tooling using the ["Instrument now, test later, collect coverage after that](https://github.com/SteveGilham/altcover/wiki/Modes-of-Operation#instrument-now-test-later-collect-coverage-after-that)" approach; during the test phase the instrumentation output is effectively write-only, and concurrency is achieved by using as many temporary files as needed, one per thread across all concurrent test processes.  The test processes even can be `dotnet test --nobuild` _without invoking AltCover_ if the instrumentation is done `--inplace`.

Then, only when all the writing is done, the results can be gathered up without worries about interference. As the coverage file name is extended to give names to the intermediate data files generated in the coverage recording process, this is not something as simple as serializing file access to the coverage file itself for concurrent collection.

**Comment by headshog** [comment]
Thanks, that worked!
