### ISSUE TITLE
Per-test level code coverage

### ISSUE THREAD

**Issue by mcintyre321** [SteveGilham/altcover#224]
Hi, I was wondering if altcover supports generating per-test level code coverage reports? We're looking for this feature so we can instrument our integration tests and only run those which don't touch any changed code.

thanks!

**Comment by SteveGilham** [comment]
The `--callContext` option tags visits according to the call stack, as a generalization of the OpenCover `-coverbytest`; a sequence point record will look like
```xml
                <SequencePoint vc="2" uspid="0" ordinal="0" offset="0" sl="8" sc="23" el="8" ec="28" bec="0" bev="0" fileid="1">
                  <Times />
                  <TrackedMethodRefs>
                    <TrackedMethodRef uid="5" vc="1" />
                    <TrackedMethodRef uid="6" vc="1" />
                  </TrackedMethodRefs>
                </SequencePoint>
```
with the tracked methods similarly having records like
```xml
        <TrackedMethod uid="5" token="100663319" name="System.Void Tests.Problematic::Thing Rectangle()" strategy="[Test]" entry="638513019427084217" exit="638513019427193380" />
```

The `<Times />` record is a generalization that records wall-clock time of visit, when requested, for the purpose of determining visits by test during scripted or manual operational  test runs.

**Comment by SteveGilham** [comment]
Assuming silence as assent, closing.
