### ISSUE TITLE
test run duration degredation when upgrading from 8.8.74 to 8.8.165?

### ISSUE THREAD

**Issue by kimpenhaus** [SteveGilham/altcover#227]
hey @SteveGilham 

I hope this doesn't come across as unqualified, but I wanted to share my observations and would like to get your feedback.

Today, Renovate gave us a PR for the version upgrade from 8.8.74 to 8.8.165. When running our PR pipeline, I noticed that the test duration has increased significantly.

Normal run duration of the unit-test step was around 4~6 minutes:

<img width="740" alt="grafik" src="https://github.com/user-attachments/assets/5cc9a6f3-d19e-434e-90fd-01a6c5136738">

After upgrading to the latest version, this step increased to over 13 minutes:

<img width="708" alt="grafik" src="https://github.com/user-attachments/assets/fe523cb5-ef35-4003-a003-a05326c508b6">

I re-ran the whole pipeline to ensure it wasn't an issue caused by machine load or something similar - the result was nearly the same:

<img width="716" alt="grafik" src="https://github.com/user-attachments/assets/a0b9716c-3ddc-45cf-9072-023984f5eccd">

I'm not sure what additional information I can provide, but I would appreciate any feedback and am happy to provide it.

Thanks,
Marcus

**Comment by SteveGilham** [comment]
Thank you for the report, unwelcome though the news is.

Of the two significant changes in this release, the recorder rewrite would be the more pervasive, and the more likely culprit. I had hoped it would make little impact, and perhaps more performant by eschewing the extra allocations required with immutable data structures - the AltCover self-tests having shown no noticeable change.

One easy way to find out, if you could be so good as to oblige - here is a build taken from the point immediately before the recorder rewrite began, but after the Cobertura fix.  If you could give this a try, that should give a definitive answer as to where the problem lies

[nupkgs.zip](https://github.com/user-attachments/files/16350460/nupkgs.zip)

If it is the recorder, then I can scrap that change, put out a new release now, and then get an alternative strategy ready for net9.0 in November.

**Comment by kimpenhaus** [comment]
Good Morning @SteveGilham,

I needed to swiutch from the azure pipeline to my local machine to run the tests with the version you gave me.

I tried to leave the machine doing its stuff with no interaction - so that the results are more or less comparable.

I then changed the version to:
 - 8.8.74
 - 8.8.90-pre-gdeef884004
 - 8.8.165
 
I did alsways a `dotnet restore` and a `dotnet build -c Release --force`

and then started with the command:

```
dotnet test Solution.sln --logger trx --results-directory ./_temp --nologo --no-build --configuration Release /p:CopyLocalLockFileAssemblies=true /p:AltCover=true /p:AltCoverFailFast=true /p:AltCoverAssemblyFilter='^(?!Some\.Namespace).*$|^(Some\.Namespace.*?\.Test.*)$' /p:AltCoverAttributeFilter=ExcludeFromCodeCoverage /p:AltCoverCobertura=coverage.cobertura.xml
```

the results were as follows:

<img width="2210" alt="grafik" src="https://github.com/user-attachments/assets/4323bf8d-b988-44da-b110-eff1e20f3dca">

<img width="2196" alt="grafik" src="https://github.com/user-attachments/assets/7c78af1e-de0c-4321-a830-ba6d83ebe7ca">

<img width="2212" alt="grafik" src="https://github.com/user-attachments/assets/d25d05a6-ffa4-454f-b419-341522b47d38">

As you can see there - unfortunately - no difference between `8.8.90-pre-gdeef884004` and `8.8.165`. So it might be the cobertura fix kickin in - not sure if that is optimizable at all or the state we have to live with 

Hope that helps - if you need further information or any other testings - just let me know. I am happy to help with that.

m.

**Comment by SteveGilham** [comment]
Thank you for that. Not the result I had hoped for.

Could you confirm that you are actually opting to generate Cobertura output (via `/p:AltCoverCobertura=...` or equivalent), as that change would only affect the reformatting part of the process.  The only other differences will be in the versions of third-party libraries used, which will be a tedious thing to track down.

**Comment by kimpenhaus** [comment]
hope I understood you correctly as I am not a native speaker (guess you figured this already 😄)

yes we are having `/p:AltCoverCobertura=coverage.cobertura.xml` as parameter (see the long dotnet test Solution.sln (at the end))

**Comment by SteveGilham** [comment]
My apologies, I had missed the command line, having simply focused on the elapsed time.

Now I know where to look.  Thank you!

**Comment by kimpenhaus** [comment]
Good morning @SteveGilham,

today I gave it another shot with also setting the `/p:AltCoverSingle=true` flag - I thought I try to see if that makes any difference - unfortunately it does not

<img width="2840" alt="grafik" src="https://github.com/user-attachments/assets/02e30cf1-7568-4e0a-bd12-311d5725926e">

I thought you might be interested in that as well - if there are other things you might think might improve perf or is worth to try just let me know.

👋🏼

**Comment by SteveGilham** [comment]
The change in behaviour is to do with processing the file names, which
depends on the purely static number and distribution of classes amongst
them, not the visits actually made.  Examining the changes I made, I can
see several possible sources of inefficiency, so at the moment I'm setting
up a proper performance test so I can measure how effective any mitigations
are.

**Comment by SteveGilham** [comment]
A proper soak test showed that the bottleneck was indeed where I though it would be, and also verified that there were no more hotspots after the fix I made, which brought performance back to where it had been.  Here's an interim build for your use -

[nupkgs.zip](https://github.com/user-attachments/files/16391179/nupkgs.zip)

**Comment by kimpenhaus** [comment]
Oh that is awesome 🙏 oder the weekend I am off with the family but as soon as i will be back home again, I'll run some tests. Thanks for fixing it that fast!

**Comment by SteveGilham** [comment]
It's also in new release v8.8.173

**Comment by kimpenhaus** [comment]
hey @SteveGilham,

I can confirm that the test run speed is as good as it was before :) thanks for fixing it that quickly and for allt he time you spent in this project!

m.
