### ISSUE TITLE
Changed source paths/filenames in 8.8.173 in combination with reportgenerator

### ISSUE THREAD

**Issue by SteveGilham** [SteveGilham/altcover#229]
### Discussed in https://github.com/SteveGilham/altcover/discussions/228

<div type='discussions-op-text'>

<sup>Originally posted by **kimpenhaus** August 15, 2024</sup>
Good morning @SteveGilham,

sorry bothering you again :) We've noticed a change in the generated cobertura files from 8.8.74 to 8.8.173 in the way the source elements and the filenames are generated.

I don't see an issue in this per se but with our setup the changes breaks the coverage analysis. we have a multi-projekt/assembly setup in azure that generated the code coverage with altcover in cobertura format and uses reportgenerator to "transform" this into single file cobertura and sonarqube generic format.

When updating to the latest version we realised that the reportgenerator threw lots of file not found warnings. drilling this down leeds us to the changes done by the new altcover verion. I will try to explain further:

In 8.8.74 it seems thet all filenames were absolute and the sources seem to contain all directories

assembly 1 (sample):

<img width="1850" alt="grafik" src="https://github.com/user-attachments/assets/7e576e6c-aebc-4c54-8300-adfcfefebdbe">
 
<img width="1668" alt="grafik" src="https://github.com/user-attachments/assets/9c0f70d5-83d2-4e2c-bbb3-6dc7f31ebf37">

assembly 2 (sample):

<img width="1456" alt="grafik" src="https://github.com/user-attachments/assets/ec6f8fc8-b501-4d8b-a4e3-315cf6f220c3">

<img width="1594" alt="grafik" src="https://github.com/user-attachments/assets/f803c85f-f7bb-496f-ab23-6c48abe2074f">

With the new 8.8.173 version same sources this seems to have changed in the way that sources contains the lowest common denominator (hopefully you understand what I mean with that :)) dircotryname and the filenames are relative to that:

assembly 1 (sample):

<img width="666" alt="grafik" src="https://github.com/user-attachments/assets/a5960e4e-9717-43f2-b8cb-985b15f37ee3">

<img width="1452" alt="grafik" src="https://github.com/user-attachments/assets/6f4cddcf-1ea0-480f-9269-15ce8479f145">

assembly 2 (sample):

<img width="1454" alt="grafik" src="https://github.com/user-attachments/assets/3382f723-f23a-4a21-adcb-f4978ec568d2">

<img width="474" alt="grafik" src="https://github.com/user-attachments/assets/4544944f-ed3a-4ff1-80bd-22b2472e8333">

the change itself looks conclusive and recduces the size of the generated files - so I don't see an issue here itself.

But when heading to reportgenerator we have the problem that the reportgenerator won't find these files.

What we tried is to set the `sourcedirs` parameter to `/agent/_work/1/s/src` but that will only fix those that matches with that directory in the sources. In the given samples `/StringExtensions.cs` would not be found as the filename is not relative to `/agent/_work/1/s/src`.

<img width="3208" alt="grafik" src="https://github.com/user-attachments/assets/36f06bc6-8b41-44e2-b149-dcefa89d7cc6">

as the assemblies (and maybe future assemblies) might vary in what sources will contain we have no idea what to set in the `sourcedirs` to cover this in general.

So our question is: Is there a way to have a root source directory which tells altcover to generate all sources and filename relative to that? So that we cann have `/agent/_work/1/s/src` in altcover and in reportgenerator?

Thanks for any suggestion 🙏🏼 

</div>

**Comment by SteveGilham** [comment]
This change was intended as a resolution to issue #197, and also to bring the output into conformance with the original cobertura format, based as it is on the Java behaviour of keeping file path and full class name in step with one another.

It should be extracting longest common leading paths - in this case it should be extracting `/agent/_work/1/s/src`, or at worst `/agent` directly. As it clearly isn't doing that, there's a bug somewhere in the process.

**Comment by SteveGilham** [comment]
The leading common path extraction is [coverage-report wide](https://github.com/SteveGilham/altcover/blob/f95d6daeaac6fc4221dde6513060e5a64d1a0adc/AltCover.Engine/Cobertura.fs#L124); with multiple independent reports being consolidated, each would have its own local root path.

**Comment by SteveGilham** [comment]
Looks like there's an easy enough resolution - allow user specification one or more package roots like `"C:\this, D:\that\or\The\other"` (or `"/this", "\that\or\the\other"`) and just add those to the mix.

**Comment by SteveGilham** [comment]
Should be resolved in v8.9.3

**Comment by kimpenhaus** [comment]
@SteveGilham - thanks again for fixing it such quickly - I just gave it a shot and that looks very good:

<img width="2844" alt="grafik" src="https://github.com/user-attachments/assets/d44b0880-ceba-4507-ae86-40310b9f7a5a">


the rport was generated with no error:

<img width="1684" alt="grafik" src="https://github.com/user-attachments/assets/e304c7b1-9642-4e3d-99f7-27260f779485">


Thanks Steve!
