### ISSUE TITLE
COM Server C# Code Coverage

### ISSUE THREAD

**Issue by MrCurio** [SteveGilham/altcover#230]
I'm using the latest AltCover global tool to keep track of the coverage of a simulator written in C#. This simulator is an out-of-process COM server. The COM server is registered and exercised via COM client written in another language. The code is written for Net Framework 4.7.2.

First thing I do is instrumenting the code with the following command:
AltCover --inputDirectory . --outputDirectory ./coverage

Then, I register the instrumented code of the "/coverage" folder with the following command:
program.exe /regserver

After, I execute the COM client to exercise the code, but seems that the coverage is not being tracked since it is all 0%. 

When running the executable manually (double clicking) the coverage is tracked perfectly. However, by the nature of COM servers, when double clicked it is only for registering or unregistering the COM server. On the other side, the COM client creates a server instance to start sending and receiving information. 

@SteveGilham any ideas what could it be wrong? Is this actually possible?

Thank you so much

**Comment by SteveGilham** [comment]
My first suspicion with this evidence is that the service is running with
an identity that doesn't have write access to the folder containing the
coverage report file, but when you personally are running it, you, of
course, do have sufficient privilege.

Having checked the wiki, I can see that I've only made an off-hand (and
since spring 2018, when "collect" mode was introduced, incomplete) mention
in passing of that requirement under the Windows Service use case
<https://github.com/SteveGilham/altcover/wiki/Use-Cases#use-case--windows-service>.


If using "classic mode
<https://github.com/SteveGilham/altcover/wiki/Modes-of-Operation#instrument-now-test-later-classic-mode>",
then write access to the report file by the service is all that is
required; but if using the collect mode of operation, write access is
required to the containing directory, for the output of the coverage visit
data during the service operation.

**Comment by MrCurio** [comment]
Hi @SteveGilham , 

I really appreciate your fast response!

I've done some digging and here's more complete information:

- I'm currently using the Instrument Now, Test later "classic mode".  
- I've added write access to the full executable and assemblies directory. In fact, a log file is created and written with the communication. Like this, I was sure I could write easily from the code. 
- The program is not a Windows Service, it is a COM Server. This affects the way the code is executed. In fact, I've realized that the "Main" method is not being called when the COM client is instantiating the server. The "main" is only called when registering the server or running the executable manually (double clicking).
- The registered server is the instrumented one. 

Despite trying to find information online, Wiki and everywhere, i cannot seem to find a way to track the coverage.

This is the C# code that defines the COM Server. This is not the "main":

```
namespace COMServer
{
    /* Interface for COM server */
    [ComVisible(true)]
    [Guid(CompanyProject.Constants.IID)]
    [InterfaceType(ComInterfaceType.InterfaceIsDual)]    
    //[InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
    public interface ISim
    {
        void OpenHandle(out int Handle);
        void CloseHandle(int Handle);
        void Request(int Handle, string Input, out string Output);
    }

    /* Class for COM server */
    [ComVisible(true)]
    [Guid(CompanyProject.Constants.CLSID)]
    //[ClassInterface(ClassInterfaceType.AutoDispatch)]
    [ClassInterface(ClassInterfaceType.None)]
    [ComDefaultInterface(typeof(ISim))]
    [ProgId(CompanyProject.Constants.ProgId)]
    
```

When the COM server is instantiated, the "OpenHandle" method is called and executed. Similarly, "Request" for sending/receiving information and "CloseHandle" when done

Any help would be much appreciated since I don't find any alternatives for this problem

Thank you

**Comment by SteveGilham** [comment]
Windows service, web application, COM server - the important thing is that these are cases where the code in an operation test is unlikely to be running as the same as principal to the one that performed the instrumentation (unlike unit tests). For coverage to be recorded during the  `ProcessExit` handler's operation, it is the principal under which the process is running that needs to be able to write to the report.

In an "is it plugged in?" check, note that the coverage report is referred to by absolute path, unless the `--portable` option is used, in which case it is co-located with the recorder; this has implications on the use when the test is performed  elsewhere than the instrumentation.

The instrumentation process interlaces the supplied code (within the constraints of filters and such) with calls out to the recorder assembly `AltCover.Recorder.g.dll`, so the route whereby the code is entered is immaterial - hence collecting coverage from libraries with no true entry-point method.

**Comment by MrCurio** [comment]
I have placed all the instrumented code under a subfolder called "coverage", which has write access permissions. I've also added some extra code to the application to append some dummy text to the coverage report (coverage.xml), to verify it has write access. 

I tried this command `AltCover --inputDirectory . --outputDirectory ./coverage` with relative and absolutes paths also including the `--report /absolute/path/to/coverage.xml`. Also, tested the `--portable` option. 

However, still no progress.  I'm kind of lost of what else I should or could try/review. 

Would you advice me to check anything in particular? Is the coverage working for both x64 and x86? 

Thank you so much for your help!

**Comment by MrCurio** [comment]
Hi @SteveGilham , 

I think I've found the issue and the solution. Since you mentioned that the report was written in the `ProcessExit ` handler, I was wondering if it was being triggered. So I simply added the line `Environment.Exit(0); // Force the process to exit` to make sure the handle was triggered and that did the trick!

Thank you so much also for your support and your great work!!
I proceed to close the issue 👍

**Comment by SteveGilham** [comment]
An alternative would have been to go to the collect style, using the coverage pause and resume capability, intended for collecting data from long-running processes that may not always get terminated when the testing stops. That uses a file deletion event to replace the process exit, for signalling that collected data should be flushed.
