### ISSUE TITLE
Support sampling or other ways to reduce coverage data collection

### ISSUE THREAD

**Issue by peteroupc** [SteveGilham/altcover#24]
Currently, AltCover seems to collect data _every time_ a given line in the code is visited.  This slows down the coverage testing significantly, by several orders of magnitude &mdash; especially when I only want to know _whether_ each line of code was visited, not necessarily _how often_ it was visited or which methods called the code in question.

Therefore, to reduce coverage testing time, AltCover should support statistical sampling and/or options for choosing the level of detail of data to collect.

**Comment by SteveGilham** [comment]
I can see how "count once if visited" could be done, at least on a per app-domain basis (otherwise you'd exchange the bottleneck which is the serialization-to-file for one of synchronizing every step on a mutex).

At the moment in self-tests the coverage drag is comparable with either OpenCover or coverlet (at least since build 3.5.543); getting to be faster then either, at least in such scenarios, would be nice.

**Comment by peteroupc** [comment]
Reducing data collection is especially needed because as of version 3.5.560 (I think &mdash; AltCover appears to have no way to print the version number), processing the coverage data after the tests complete (with `runner --collect`) takes many times longer than collecting that data while the tests are running.

For example, as of now, the NUnit unit tests complete in under 4 minutes, but AltCover doesn't finish processing the resulting coverage data (`acv`), which is about 5 MB in size and contains almost 8 million recorded visits, within 30 minutes.  

I am aware that [you wrote](https://github.com/SteveGilham/altcover/issues/22) that the "process is limited by the file I/O both during the test running and again during the post-processing (somewhere around 50k visits processed per second in each phase), and this dominates the process".  For me, however, the testing phase appears manageable (I can set a timeout for each unit test via the NUnit command line).

**Comment by SteveGilham** [comment]
New release [3.5.569](https://www.nuget.org/packages/AltCover/3.5.569) has a number of options to reduce the amount of data being transmitted (`--single`, `--linecover` and `--branchcover`); using `--single` in the build reduces some of the intermediate files a thousand-fold in size in that context.
