### ISSUE TITLE
Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by latop2604** [SteveGilham/altcover#26]
I'm try to use altcover (globaltool 3.5.569) to generate coverage for my netcore 2.1 app, using "Instrument now, test later, runner mode"

But half of my tests failed with the error message "System.InvalidProgramException : Common Language Runtime detected an invalid program."

And then the report can still be generated (reportgenerator) but is partial.

I use theses commands : 

```bash
altcover --opencover -o=__saved_cart --inplace -c=0 "-c=[Fact]" -x cart.opencover.xml -i api-cart/src/Cart.Tests/bin/Debug/netcoreapp2.1/ --fileFilter=Reference.cs
altcover Runner -x dotnet -r api-cart/src/Cart.Tests/bin/Debug/netcoreapp2.1 -- test api-cart/src/Cart.Tests --no-build --no-restore
```

```
Nombre total de tests : 57. Réussis : 34. Non réussis : 23. Ignorés : 0.
Échec de la série de tests.
Durée d'exécution des tests : 12,4410 Secondes
Getting results...
... /Users/xxx/xxx/cart.opencover.xml.0.acv (32 175b)
13 420 visits recorded in 00:00:00.1235400 (108 629 visits/sec)
A total of 13 420 visits recorded
Coverage statistics flushing took 0,513 seconds
Visited Classes 33 of 332 (9.94)
Visited Methods 125 of 689 (18.14)
Visited Points 510 of 4748 (10.74)
Visited Branches 60 of 1512 (3.97)
==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 33 of 449 (7.35)
Alternative Visited Methods 125 of 1135 (11.01)
```

If a use the nuget package `AltCover` everything seem ok.

**Comment by SteveGilham** [comment]
This will be something similar to issues #13, #14 and #15, where there's some IL idiom I've not used in any of my test code so far, so this is going to come down to finding a cut-down repro.  Running PEVerify over the failing assembly should indicate where things have been broken.

My first suspicion is that this will be in the unit tests, as managing the tracking context is quite invasive, and that is what caused the problems in the previous issues (that can be tested by omitting the `-c` arguments).

**Comment by latop2604** [comment]
Arf, ok. I will try to find a repro

**Comment by latop2604** [comment]
I run my test again without the -c parameter. And everything seem ok. All test pass.
Maybe should be a good idee to remove it from the [wiki page](https://github.com/SteveGilham/altcover/wiki/Examples-of-use)

**Comment by SteveGilham** [comment]
I expected that the problem would be that the adding the tracking instrumentation would be what broke the IL; and that the tests would run OK without that (and that the tracking information would probably not be of significant use to you).

I would still be interested in finding what it was in your unit tests that I managed to break, so if you do ever manage to get a simple repro, please do pass it to me.

**Comment by SteveGilham** [comment]
Wiki page updated; I'll leave it up to you whether you want to close the issue now you're unblocked.

**Comment by SteveGilham** [comment]
Closing for the moment as no repro; leaving as an open ticket on [the current kanban](https://github.com/SteveGilham/altcover/projects/6).

**Comment by ffMathy** [comment]
This is exactly what I was experiencing in #105, which has been resolved now.
