### ISSUE TITLE
Unable to Exclude Folders

### ISSUE THREAD

**Issue by RichardD012** [SteveGilham/altcover#27]
Maybe I'm misreading the command line parameters and instructions, but its unclear if I'm able to call AltCover to completely ignore a subset of directories.

Calling from (based on instructions its regex so the .* should define wildcard path):
`dotnet test -v n /p:AltCover=true /p:AltCoverMethodFilter=.\*/src/Data/Generated/.\*/.\*.cs` 

all files matching our generated code in src/Data/Generated still show up in the output report.  The usage instructions could use some concrete examples of how to properly use these flags as I'm expecting it to take standard wildcard paths which doesn't seem to be the case.

**Comment by RichardD012** [comment]
Thanks this actually clears up a lot.  I was thinking full path file filter.

Also, I totally copied and pasted the wrong attribute there so of course that doesn't work.

**Comment by SteveGilham** [comment]
[Pre-release build 3.5.577](https://ci.appveyor.com/project/SteveGilham/altcover/build/3.5.577-pre/artifacts) has a new -pathFilter (/p:AltCoverPathFilter) parameter that should do what you're looking for.  As always the test is "does the regex match at all", not "does the regex match the entire string".

**Comment by SteveGilham** [comment]
And formally in release 3.5.580
