### ISSUE TITLE
Question about merging results

### ISSUE THREAD

**Issue by risogolo** [SteveGilham/altcover#30]
Since dotnetcore's behavior when testing entire solution is trying also test non testing projects and then whole process is evaluated as non successful at least on linux, then I need to run test on one by one testing project separately I need to somehow then merge  altcover results into one xml file, is that possible?

**Comment by SteveGilham** [comment]
Merging separate coverage reports -- the sort of thing that the venerable NCoverExplorer did for NCover format --  at the raw XML level is [on the roadmap](https://github.com/SteveGilham/altcover/projects/6#card-10569725), but still only at the TODO stage of the kanban.

In the interim, ReportGenertor 3.x will run under Mono to combine a mix of raw coverage files into various forms of summary report -- the AltCover build uses it on both Windows and Linux CI platforms to monitor its own coverage; and the 4.0 RC also offers .net core support (though not yet as a DotnetCLITool nor a global tool).

**Comment by SteveGilham** [comment]
Scratch that -- there are CLI and global tool options for report generator now (they appeared in the last few days, i.e. since I last looked).

**Comment by risogolo** [comment]
But sill would be fine incorporate that functionality directly, I'm using SonnarQube so then I have no need to use report generator since it supports the generated xml's directly

**Comment by TheAngryByrd** [comment]
Isn't https://github.com/SteveGilham/altcover/blob/ca0704ce1144b7860006f57843c2170ba3fb43e8/Build/targets.fsx#L682-L703 basically doing this?

**Comment by SteveGilham** [comment]
That's a naive concatenation of coverage files that is fortunately sufficient for coveralls; it doesn't consolidate the two sets of coverage for the main assembly (altReport, xaltReport) into one, and it doesn't fill in all the summary fields, so I don't know how digestible it would be for SonarQube like that.

**Comment by bgeorgeiii** [comment]
FWIW, the issue with "dotnet test" against solutions with mixed projects was repaired in I believe version 15.9 of the test framework. You can now run it without receiving errors for non-test projects. This means you can also achieve parallel running of the tests which would be difficult, if not impossible, running dotnet test individually on each test project.

**Comment by SteveGilham** [comment]
Thanks for that information.  I shall have to try it out in the AltCover self-test, and see what happens, and whether there are any new problems for me to fix.

As to the original issue -- that nobody has written an OpenCover merge that matches NCoverExplorer's functionality (because there are a lot of corner cases to deal with, especially if it includes merging the subtly different output from OpenCover, AltCover and Coverlet) -- well, it will depend on how many other things crop up over the winer.

**Comment by SteveGilham** [comment]
By experiment, it's SDK 2.1.500 that fixes the errors on non-test projects, when running `dotnet test` on a solution.

**Comment by SteveGilham** [comment]
Finally - v8.1.817 offers the `Merge-OpenCover` cmdlet and associated API for merging `OpenCover` format output, doing its best to reconcile different dialects that yield slightly different output even when running on the exact same test build.  It was the doing reconciliation bit in a simple and testable way that took the time.

As OpenCover format is the primary format offered by AltCover, and there are cmdlets/APIs to take other output to and from that format, I think that resolves this issue.
