### ISSUE TITLE
coverage.xml and multiple target frameworks

### ISSUE THREAD

**Issue by TheAngryByrd** [SteveGilham/altcover#31]
I'm updating to the latest version of Altcover in MiniScaffold https://github.com/TheAngryByrd/MiniScaffold/issues/94.

The issue I'm seeing is when running `dotnet test /p:AltCover=true` and  having multiple target frameworks such as `<TargetFrameworks>netcoreapp2.1;netcoreapp2.0;net461</TargetFrameworks>`, it will constantly wipe over the coverage.xml.  

The options I can think of are

1.  Put the coverage.xml in the output folder `bin/Release/netcoreapp2.1` 
2. Template the coverage.xml to something like `coverage.netcoreapp2.1.xml`
3.  Somehow merge the results

Thanks for the help!

**Comment by SteveGilham** [comment]
I'm going with option 2 -- until I assemble a release, [the delta is here](https://github.com/SteveGilham/altcover/commit/a86f85bd7c5e1ba66ab123c3b58d4143e63dae25)

**Comment by SteveGilham** [comment]
And fixed in release 4.0.600
