### ISSUE TITLE
Generating cobertura output doesnt seem to be possible like the wiki suggests

### ISSUE THREAD

**Issue by tomecho** [SteveGilham/altcover#32]
I tried running `dotnet test /p:AltCover=true /p:CopyLocalLockFileAssemblies=true /p:Cobertura=coverage.xml` however the Cobertura parameter is ignored and the default open cover format is still generated.

When I manually build, inject the altcover IL and the collect using the runner it is able to output to cobertura format.

**Comment by SteveGilham** [comment]
All the MSBuild parameters for altcover are prefixed with `AltCover`, so the command-line you want is 
```
dotnet test /p:AltCover=true /p:CopyLocalLockFileAssemblies=true /p:AltCoverCobertura=coverage.xml
``
The process will first generate an OpenCover format report with the default name `coverage.xml`, run the test, fill it in, then postprocess and, as the chosen file has the same path, overwrite with Cobertura format.

**Comment by tomecho** [comment]
Thank you for the quick response.  The wiki should be updated to reflect this, this page suggests otherwise.
https://github.com/SteveGilham/altcover/wiki/QuickStart-Guide

**Comment by SteveGilham** [comment]
Thanks -- I'd updated the `dotnet test` integration page, but forgotten the Quick Start also brought in some other examples.   Now fixed.

**Comment by tomecho** [comment]
Thank you, great project btw!
