### ISSUE TITLE
Which GTK+3 theme does altcover.visualizer require?

### ISSUE THREAD

**Issue by bentayloruk** [SteveGilham/altcover#36]
I've installed altcover.visualizer as a global dotnet core tool and am launching it from iTerm on macOS.  Upon launch, a whole bunch of errors appear in the console relating to assets missing from the theme Adwaita (see below).  I've tried to find reference to a required theme in the docs, but have not found anything.  Does altcover require a particular theme?

I can open my coverage XML despite the errors, but the visualizer is blank.  I'm not sure if this is related to the theming issue or is something else.  Any tips appreciated! 

![image](https://user-images.githubusercontent.com/189409/46425460-a9c01f00-c733-11e8-9027-aaf00ab5ca67.png)

```

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:42.907: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:42.950: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:42.951: Error loading theme icon 'help-about' for stock: Icon 'help-about' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:42.951: Error loading theme icon 'application-exit' for stock: Icon 'application-exit' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:54.719: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:54.724: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:55.732: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:57.981: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:57.982: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:57.982: Error loading theme icon 'help-about' for stock: Icon 'help-about' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:57.982: Error loading theme icon 'application-exit' for stock: Icon 'application-exit' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:57.996: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:57.997: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:57.997: Error loading theme icon 'help-about' for stock: Icon 'help-about' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:57.997: Error loading theme icon 'application-exit' for stock: Icon 'application-exit' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:58.027: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:58.028: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:58.028: Error loading theme icon 'help-about' for stock: Icon 'help-about' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:58.028: Error loading theme icon 'application-exit' for stock: Icon 'application-exit' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:58.030: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:58.030: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:58.031: Error loading theme icon 'help-about' for stock: Icon 'help-about' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:58.031: Error loading theme icon 'application-exit' for stock: Icon 'application-exit' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:58.050: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(AltCover.Visualizer:20783): Gtk-WARNING **: 17:30:58.050: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Ad

```

**Comment by SteveGilham** [comment]
On the theme issue -- I used whatever the default out-of-the-box theme is for both the GTK2 and GTK3 installs in the screen shots I took, but I expect the answer to be "any theme that includes images for the GTK stock icon names as listed".  Having not played with that side of things, I didn't expect that there would be no graceful fallback to the defaults for incomplete themes.

The tree view doesn't auto-expand; you have to drill down manually to get to the function you want to explore.

**Comment by bentayloruk** [comment]
Thanks for the response Steve.  I'm a newbie with GTK, so will try and figure out what is going on.  My reading suggests that Adwaita is the default theme for GTK+3, but maybe it's messed in my install or something.  Will do some digging.

I did try and drill down on the tree, but nothing happens.  By drill down, I mean double click on the   coverage.xml.  I also tried a right click to see if there was an expand option.  However, maybe this is related to the theme issue.  I'll try and get that fixed first and then see what happens.

**Comment by SteveGilham** [comment]
Having checked [the current GTK+3 documentation on the subject](https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html), it looks like this may be what is going on:

> Since GTK+ 3.10, stock items are deprecated. 

The only icon that comes through, the one for font selection, is documented as 

> `"gtk-select-font"` ... has been deprecated since version 3.10 and should not be used in newly-written code.

whereas the others are like 

> `"gtk-open"` ... has been deprecated since version 3.10 and should not be used in newly-written code.  Use named icon "document-open" or the label "_Open".

so my guess is that that the theme instance you are using has icons with the old names, but GTK is translating the old names in the code to the new names where new preferred names are documented, and those new names aren't in the theme.

Since the standard message-box dialogs also use stock items for status icons (warning, information, etc.) , this might be interfering with any messages raised about the coverage file -- waiting on a message-box that's a no-show would explain the non-responsive behaviour you are seeing.

**Comment by SteveGilham** [comment]
As this is not something I can repro locally, here's a build of the visualizer that will produce some debug trace information about what it finds in the way of stock items (lines on the console starting `DEBUG: `); it will also dump message and severity for any message boxes that it is about to display.

[visualizer.zip](https://github.com/SteveGilham/altcover/files/2449532/visualizer.zip)

unzip and `dotnet  path/to/AltCover.Visualizer.dll` to run.  It may give some clues abotu detecting what's happening so it can be coded around.

**Comment by bentayloruk** [comment]
Amazing, thanks Steve.  I was just sitting here with the morning coffee, trying to figure out the themes.  Can't believe I'm struggling with getting a theme to install and work!

Anyway, I've done what you asked and this is the output from just running the visualizer.  I've not then clicked on anything or tried to do anything with the visualizer.

```
~/Downloads/_Publish.visualizer
09:44 $ dotnet AltCover.Visualizer.dll

(AltCover.Visualizer:37259): Gtk-WARNING **: 09:44:26.806: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(AltCover.Visualizer:37259): Gtk-WARNING **: 09:44:26.843: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

(AltCover.Visualizer:37259): Gtk-WARNING **: 09:44:26.843: Error loading theme icon 'help-about' for stock: Icon 'help-about' not present in theme Adwaita

(AltCover.Visualizer:37259): Gtk-WARNING **: 09:44:26.844: Error loading theme icon 'application-exit' for stock: Icon 'application-exit' not present in theme Adwaita
DEBUG: Stock.Open -> "gtk-open"
DEBUG:  "gtk-zoom-out"
DEBUG:  "gtk-zoom-in"
DEBUG:  "gtk-zoom-fit"
DEBUG:  "gtk-zoom-100"
DEBUG:  "gtk-yes"
DEBUG:  "gtk-unindent"
DEBUG:  "gtk-undo"
DEBUG:  "gtk-underline"
DEBUG:  "gtk-undelete"
DEBUG:  "gtk-strikethrough"
DEBUG:  "gtk-stop"
DEBUG:  "gtk-spell-check"
DEBUG:  "gtk-sort-descending"
DEBUG:  "gtk-sort-ascending"
DEBUG:  "gtk-select-font"
DEBUG:  "gtk-select-color"
DEBUG:  "gtk-select-all"
DEBUG:  "gtk-save-as"
DEBUG:  "gtk-save"
DEBUG:  "gtk-revert-to-saved"
DEBUG:  "gtk-remove"
DEBUG:  "gtk-refresh"
DEBUG:  "gtk-redo"
DEBUG:  "gtk-quit"
DEBUG:  "gtk-properties"
DEBUG:  "gtk-print-warning"
DEBUG:  "gtk-print-report"
DEBUG:  "gtk-print-preview"
DEBUG:  "gtk-print-paused"
DEBUG:  "gtk-print-error"
DEBUG:  "gtk-print"
DEBUG:  "gtk-preferences"
DEBUG:  "gtk-paste"
DEBUG:  "gtk-page-setup"
DEBUG:  "gtk-orientation-reverse-portrait"
DEBUG:  "gtk-orientation-reverse-landscape"
DEBUG:  "gtk-orientation-portrait"
DEBUG:  "gtk-orientation-landscape"
DEBUG:  "gtk-open"
DEBUG:  "gtk-ok"
DEBUG:  "gtk-no"
DEBUG:  "gtk-new"
DEBUG:  "gtk-network"
DEBUG:  "gtk-missing-image"
DEBUG:  "gtk-media-stop"
DEBUG:  "gtk-media-rewind"
DEBUG:  "gtk-media-record"
DEBUG:  "gtk-media-previous"
DEBUG:  "gtk-media-play"
DEBUG:  "gtk-media-pause"
DEBUG:  "gtk-media-next"
DEBUG:  "gtk-media-forward"
DEBUG:  "gtk-leave-fullscreen"
DEBUG:  "gtk-justify-right"
DEBUG:  "gtk-justify-left"
DEBUG:  "gtk-justify-fill"
DEBUG:  "gtk-justify-center"
DEBUG:  "gtk-jump-to"
DEBUG:  "gtk-italic"
DEBUG:  "gtk-info"
DEBUG:  "gtk-index"
DEBUG:  "gtk-indent"
DEBUG:  "gtk-home"
DEBUG:  "gtk-help"
DEBUG:  "gtk-harddisk"
DEBUG:  "gtk-goto-top"
DEBUG:  "gtk-goto-last"
DEBUG:  "gtk-goto-first"
DEBUG:  "gtk-goto-bottom"
DEBUG:  "gtk-go-up"
DEBUG:  "gtk-go-forward"
DEBUG:  "gtk-go-down"
DEBUG:  "gtk-go-back"
DEBUG:  "gtk-fullscreen"
DEBUG:  "gtk-floppy"
DEBUG:  "gtk-find-and-replace"
DEBUG:  "gtk-find"
DEBUG:  "gtk-file"
DEBUG:  "gtk-execute"
DEBUG:  "gtk-edit"
DEBUG:  "gtk-dnd-multiple"
DEBUG:  "gtk-dnd"
DEBUG:  "gtk-disconnect"
DEBUG:  "gtk-discard"
DEBUG:  "gtk-directory"
DEBUG:  "gtk-dialog-warning"
DEBUG:  "gtk-dialog-question"
DEBUG:  "gtk-dialog-info"
DEBUG:  "gtk-dialog-error"
DEBUG:  "gtk-dialog-authentication"
DEBUG:  "gtk-delete"
DEBUG:  "gtk-cut"
DEBUG:  "gtk-copy"
DEBUG:  "gtk-convert"
DEBUG:  "gtk-connect"
DEBUG:  "gtk-color-picker"
DEBUG:  "gtk-close"
DEBUG:  "gtk-clear"
DEBUG:  "gtk-cdrom"
DEBUG:  "gtk-caps-lock-warning"
DEBUG:  "gtk-cancel"
DEBUG:  "gtk-bold"
DEBUG:  "gtk-apply"
DEBUG:  "gtk-add"
DEBUG:  "gtk-about"
DEBUG: false <null>
DEBUG: true "gtk-open"
DEBUG: false <null>
```

**Comment by SteveGilham** [comment]
The big list of `DEBUG:  "gtk-*"` items is a dump of the result of a call to `gtk_stock_list_ids`; which means that we're still getting presented the old names and nothing else, with no inkling that anything is amiss.

Working from the other end of the problem ("is it plugged in?"), the `document-open` icon should be present in various sizes in directories `/usr/share/icons/Adwaita/##x##/actions`  as `document-open.png`, and the `index.theme` should include at least one of those directories in the directory list.  Any `/usr/share/icons/default/index.theme` should ideally only contain an "inherit from Adwaita" entry.

**Comment by SteveGilham** [comment]
Fair enough.  I've been learning about these nuances, now, too.

**Comment by bentayloruk** [comment]
Thanks for all your help Steve.  I'll ping you if/when I manage to figure it out.
