### ISSUE TITLE
Is instrumentation idempotent?

### ISSUE THREAD

**Issue by leighshepperson** [SteveGilham/altcover#39]
Is the instrumentation operation idempotent in the sense that instrumenting an already instrumented assembly has no additional effect, i.e. line coverage, etc...?

**Comment by SteveGilham** [comment]
Re-instrumenting an assembly comes under "undefined behaviour".  It's not an occurrence that would be expected in a typical test workflow, where a newly minted system would be instrumented every time, so it's not something I've even tested.

What sort of use-case do you have in mind here, where the issue would arise?

**Comment by leighshepperson** [comment]
The issue would only arise in a very special case for me (merged test dirs and running repeatedly over that). Since as you said it's undefined behavior, it's highlighted that the fix should be implemented elsewhere.
