### ISSUE TITLE
Codecov.io can't process generated reports

### ISSUE THREAD

**Issue by Nihlus** [SteveGilham/altcover#4]
When attempting to upload a coverage report generated by altcover to [Codecov.io](https://codecov.io), codecov accepts the file and appears to consume it, but fails with an error message on the service, claiming that no files were found in the report.

I'm unsure if this is an issue with Codecov's parsing engine, or if the format that Altcover generates is doing something funny along the line. I've reported the issue to Codecov as well (codecov/support#479), and I've included what logs I could gather.

[codecov.log](https://github.com/codecov/support/files/1740627/codecov.log)
[coverage.xml.txt](https://github.com/codecov/support/files/1740628/coverage.xml.txt)
[travis-log (1).txt](https://github.com/codecov/support/files/1740629/travis-log.1.txt)

**Comment by SteveGilham** [comment]
That you have a generated report shows that code has been instrumented; but there is zero coverage (`visitcount="0"` throughout).  That lack might be the reason for the upload failure.

I suspect that you are falling foul of the way that .net core severely restricts the time available to ProcessExit handlers compared with the traditional framework, and that the coverage data just isn't being written to the file before the axe falls.  By its very nature, alas, this is something that I can't put a warning about if it happens.

Could you try using altcover in runner mode, like
```
dotnet run --project altcover/altcover.1.6.230/tools/netcoreapp2.0/AltCover/altcover.core.fsproj --no-build -- runner -x "dotnet" -r "AdvancedDLSupport.Tests/bin/Debug/netcoreapp2.0" -- test AdvancedDLSupport.Tests --no-build
```

I also note that AltCover recorder assembly has been caught up in the instrumentation, despite the filtering.  I shall have to take a look at that as well.

**Comment by SteveGilham** [comment]
Having looked at the [codecov.io](https://docs.codecov.io/docs/supported-languages) documentation, I see the fundamental issue.

Currently, for historical reasons, altcover emits coverage data in NCover format, which is almost entirely unlike OpenCover format.  I have [a work item](https://github.com/SteveGilham/altcover/projects/3#card-6169050) planned that will address this.

**Comment by Nihlus** [comment]
Using runner mode did produce visitcounts above zero - I'm testing an upload now. I've had success with Mono's coverage format too, so I don't think Codecov is restricted to the OpenCover format.

**Comment by Nihlus** [comment]
Yeah, same issue on the Codecov end. Some type of doctoring is being applied to the report, so Codecov doesn't outright reject it. Peculiar.

```
0.95s$ bash <(curl -s https://codecov.io/bash)
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-8b76995
==> Travis CI detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
==> Searching for coverage reports in:
    + .
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Appending build variables
    + TRAVIS_OS_NAME
==> Reading reports
    + ./coverage.xml bytes=447040
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
    + Found adjustments
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=codecov-test&commit=4914e5250a431fbe0453912a3742579894662aca&build=111.1&build_url=&name=&tag=&slug=Nihlus%2FAdvanceDLSupport&service=travis&flags=&pr=false&job=344421851
    -> Pinging Codecov
    -> Uploading
    -> View reports at https://codecov.io/github/Nihlus/AdvanceDLSupport/commit/4914e5250a431fbe0453912a3742579894662aca
```

**Comment by Nihlus** [comment]
Codecov has added support for the NCover format now, so Altcover can be used out of the box :)

**Comment by jnm2** [comment]
@Nihlus I'm still getting the same failure unless I add `--opencover` to the altcover command line:

> ![image](https://user-images.githubusercontent.com/8040367/59969172-e0360800-9515-11e9-8eca-8dcc46088155.png)

Do you have a reference I can look at to see why?
