### ISSUE TITLE
Way to filter out compiler generated classes

### ISSUE THREAD

**Issue by Sidoine** [SteveGilham/altcover#44]
I try to filter compiler generated classes like those used to deconstruct dictionary key/value pairs in a foreach loop. If I use the /p:AltCoverAttributeFilter=CompilerGenerated parameter, it seems that the async methods are removed too (although AsyncStateMachinAttribute doesn't inherit from CompilerGeneratedAttribute).
What should I do?

**Comment by SteveGilham** [comment]
Unfortunately, almost any interesting C# language feature (starting with `yield return` and getting more so every update) involves generating hidden internal classes which include some or all of the user defined logic.  This all ends up making filtering on `[CompilerGenerated]` far too blunt an instrument to be much use.

For example, when you see a simple method like 
```
        public async Task<string> F3(string input)
        {
            var f = new StreamReader(File.OpenRead(input));
            var r = await f.ReadToEndAsync();
            return r;
        }
```
the actual method as compiled looks like
```
[AsyncStateMachine(typeof(<F3>d__2))]
[DebuggerStepThrough]
public Task<string> F3(string input)
{
	<F3>d__2 stateMachine = new <F3>d__2();
	stateMachine.<>4__this = this;
	stateMachine.input = input;
	stateMachine.<>t__builder = AsyncTaskMethodBuilder<string>.Create();
	stateMachine.<>1__state = -1;
	AsyncTaskMethodBuilder<string> <>t__builder = stateMachine.<>t__builder;
	<>t__builder.Start(ref stateMachine);
	return stateMachine.<>t__builder.Task;
}
```
with all the user defined logic having been moved into the `stateMachine` object whose whole type is branded `[CompilerGenerated]`.

So, the real question boils down to "what idioms in the code do you really want to ignore?", and maybe there could be a more targeted way of getting rid of what is essentially noise.

**Comment by SteveGilham** [comment]
> I try to filter compiler generated classes like those used to deconstruct dictionary key/value pairs in a foreach loop.

Meanwhile, if I build code like this
```
        public static void LoopIt(Dictionary<int, string> d)
        {
            foreach ((int key, string value) in d)
            {
                Console.WriteLine("{0} => {1}", key, value);
            }
        }
```
that simply compiles to
```
	public static void LoopIt(Dictionary<int, string> d)
	{
		foreach (KeyValuePair<int, string> item in d)
		{
			int key2;
			string value2;
			item.Deconstruct(out key2, out value2);
			int key = key2;
			string value = value2;
			Console.WriteLine("{0} => {1}", key, value);
		}
	}
```
with no `[CompilerGenerated]` code in sight.

Could you explain in more detail what it is you are wanting to filter as compiler generated noise?

**Comment by Sidoine** [comment]
I made a mistake, the compiler generated code was for another line of code, a lambda in a ToDictionary. The lambda was not covered, it was not a false positive so it should not be filtered. I'm very sorry.

**Comment by SteveGilham** [comment]
No problem.
