### ISSUE TITLE
Getting AltCover.Recorder.g.dll not found in --the nominated directory.

### ISSUE THREAD

**Issue by amitwats** [SteveGilham/altcover#46]
Until yesterday I was successfully able to run the following command for projects
`dotnet test /p:AltCover=true /p:AltCoverOpenCover=true /p:AltCoverXmlreport="C:\xxxx\temp\Unittesting\AltCover\AltCover1.json"  c:\projects\xxxx\platform\tests\server\xxx.xxxxxxx.Admin.Tests\xxx.xxxxxxx.Admin.Tests.csproj`

suddenly yesterday it started throwing an error as below. The Build Starts and Completes after that the  error it throws is 

```
C:\Users\xxxxxxxx\.nuget\packages\altcover\4.0.661\build\netstandard2.0\AltCover.targets(33,5): error : Output directory for saved files c:\projects\xxxxxxx\platform\tests\server\xxx.xxxxxxx.xxxxx.Export.Tests\bin\Debug\netcoreapp2.1\__Saved already exists [c:\projects\xxxxxxx\platform\tests\server\xxx.xxxxxxx.xxxxx.Export.Tests\xxx.xxxxxxx.xxxxxxxxxxx.Tests.csproj]

Error - usage is:
  -i, --inputDirectory=VALUE Optional: The folder containing assemblies to
                               instrument (default: current directory)
  -o, --outputDirectory=VALUE
                             Optional: The folder to receive the instrumented
                               assemblies and their companions (default: sub-
                               folder '__Instrumented' of the current directory;
                                or '__Saved' if 'inplace' is set)
```

after the list of help text is printed it gives the following error

```
Error - usage is:
C:\Users\xxxxxxxx\.nuget\packages\altcover\4.0.661\build\netstandard2.0\AltCover.targets(87,5): error : Recorder assembly c:\projects\xxxxxxx\platform\tests\server\xxx.xxxxxxx.xxxxx.Export.Tests\bin\Debug\netcoreapp2.1\AltCover.Recorder.g.dll not found in   -the nominated directory. [c:\projects\xxxxxxx\platform\tests\server\xxx.xxxxxxx.xxxxx.Export.Tests\xxx.xxxxxxx.xxxxxxxxxxx.Tests.csproj]

i, --inputDirectory=VALUE Optional: The folder containing assemblies to                           
                               instrument (default: current directory)                            
  -o, --outputDirectory=VALUE                                                                     
                             Optional: The folder to receive the instrumented                     
                               assemblies and their companions (default: sub-                     
                               folder '__Instrumented' of the current directory;                  
                                or '__Saved' if 'inplace' is set)                                 
  -y, --symbolDirectory=VALUE                                                                     
```

Any idea why this is happening? My work is stuck due to this error.

**Comment by SteveGilham** [comment]
The first message is saying that the previous run didn't completely tidy up after itself -- the `__Saved` folder is where the original binaries are copied to while the instrumented ones are being used; and the last thing that `dotnet test /p:AltCover=true` does is to run a `RemoveDir` on it after copying those original binaries back into place.

If a previous run was interrupted, then that would leave that directory behind, whereupon subsequent run swill fail because the new clean directory they're trying to create already exists.

Deleting `c:\projects\xxxxxxx\platform\tests\server\xxx.xxxxxxx.xxxxx.Export.Tests\bin\Debug\netcoreapp2.1\__Saved` (and any stale binaries in it) will unblock you.

**Comment by amitwats** [comment]
Worked like a charm ! Thanks for a quick turnaround and fixing the error message.

**Comment by SteveGilham** [comment]
The 5.0 release includes an improved error messages, and an extra flag /AltCoverForce=true to force-delete any such left-over diretory.
