### ISSUE TITLE
AltCoverAssemblyExcludeFilter does not work on Linux

### ISSUE THREAD

**Issue by maciejjarzynski** [SteveGilham/altcover#49]
When running `dotnet test` with `AltCoverAssemblyExcludeFilter` set to exclude `\.Tests`, that does not work on Debian Linux (Docker).
(it does not matter, if it contains also `xunit` for version 5.x.x, or not, for version 4.x.x of AltCover)
The command:
`dotnet test code\MyProject.sln /p:AltCover=true /p:AltCoverAssemblyExcludeFilter="\.Tests|xunit" /p:CopyLocalLockFileAssemblies="true" /p:DebugType="pdbonly" /p:AltCoverXmlreport="altcover.xml"`

The files below are ready-to-run scripts for Docker, with an assumption in `run-coverage.sh`, that this code would be placed in `c:/altcover-repro/` - that is a volume binding which is only possible with an absolute path.

[altcover-exclude-filter-repro.zip](https://github.com/SteveGilham/altcover/files/2727259/altcover-exclude-filter-repro.zip)

Dotnet info:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.502
 Commit:    c74ce8f29f

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.502/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.502 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by SteveGilham** [comment]
Something is up with the `\` character at the MSBuild level.  The raw AssemblyExcludeFilter value is reported as `\.Tests|xunit`, but the result of running `.Split('|')` is `/.Tests` and `xunit`.  It's like something is "helpfully" adjusting path separators in the process, without being asked.

**Comment by SteveGilham** [comment]
Addressed in 5.0.664

**Comment by maciejjarzynski** [comment]
That's great! I'd check that and give a feedback here.

**Comment by SteveGilham** [comment]
Assuming resolved
