### ISSUE TITLE
Problem installing package on CI build worker with platform environment variable present

### ISSUE THREAD

**Issue by OwenMcDonnell** [SteveGilham/altcover#5]
A client of ours is having a problem installing your package when running ci builds for different platforms as outlined [here](https://help.appveyor.com/discussions/problems/12764-altcover-fails-to-build-via-dotnet-run-when-the-platform-is-explicitly-specified-in-the-configuration).

If the platform environment variable is not set, the nuget installation succeeds, but if set the installation fails. 
Can you advise on what the cause of this behaviour might be or propose a better solution than the simple workaround I provided [here](https://help.appveyor.com/discussions/problems/12764-altcover-fails-to-build-via-dotnet-run-when-the-platform-is-explicitly-specified-in-the-configuration)?

**Comment by SteveGilham** [comment]
Interesting.  The failure 
```
[00:03:53] C:\projects\advancedlsupport\altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\Runner.fs(142,34): error FS0039: The value, constructor, namespace or type 'Base' is not defined. [C:\projects\advancedlsupport\altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj]
```
says that it's failing to find code from a file that is shared and linked into the main program by relative path.

**Comment by SteveGilham** [comment]
I've repro'd the problem, including the subsequent x86 image format issue; and clearing the platform (and letting it default to AnyCPU) is the best work-round for the moment.

**Comment by SteveGilham** [comment]
Analysis:
Different bitness is a dimension that slipped through my test set.
* The shared code uses a compilation constant to distinguish between whether it's in the main program (CLR4 in the full framework) or the recorder assembly (CLR2, ditto); that constant is only set when Platform is AnyCPU.  Fixing is trivial -- just hoist the constant out of the conditional PropertyGroup elements in the .fsproj file -- but is insufficient of itself.
* the 64-bit dotnet command will happily build x86 assemblies if directed through the environment variable "Platform" (though no documented command-line flag does this), but doesn't want to execute them, `dotnet run` protesting with `System.BadImageFormatException` when you try.  This seems to be the next issue that's been hit.

If the full framework is available, it would be worth trying the experiment of using the net45 version instead -- that is one of the test cases in the build, and it also with mono on Linux -- where at least you have known AnyCPU assemblies.

Meanwhile, I have a test matrix to draw up and fill in.

**Comment by SteveGilham** [comment]
So I installed the x86 build of the .net core SDK 2.1.4; and while `C:\Program Files (x86)\dotnet\` has been added to my `PATH`, it's sandwiched in-between to instances of `C:\Program Files\dotnet\`.  This means that what gets defaulted by invoking just `dotnet` is still the 64-bit version.

That means that even after I've fixed the compilation constant, running instrumentation with `%Platform%` as "x86" still blows up with `System.BadImageFormatException`.  If I specifically invoke  `C:\Program Files (x86)\dotnet\dotnet.EXE`, however, the instrumentation step works.

**Comment by OwenMcDonnell** [comment]
As you suggested i tried specifically invoking the x86 dotnet.exe based on stored platform variable condition in [this build](https://ci.appveyor.com/project/britzkopf/advancedlsupport/build/1.0.23)
(here is related batch script)
```
:: Instrument the test assemblies
if "%TEMP_PLATFORM%"=="x86" (
	"C:\Program Files (x86)\dotnet\dotnet.EXE" run^
 --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --configuration %CONFIGURATION% --^
 -i=AdvancedDLSupport.Tests\bin\%OUTPUT_DIR%\netcoreapp2.0 -o=instrumented-adl -x=coverage-adl.xml^
 --assemblyExcludeFilter=.+\.Tests --assemblyExcludeFilter=AltCover.+ --assemblyExcludeFilter=Mono\.DllMap.+

	"C:\Program Files (x86)\dotnet\dotnet.EXE" run^
 --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --configuration %CONFIGURATION% --^
 -i=Mono.DllMap.Tests\bin\%OUTPUT_DIR%\netcoreapp2.0 -o=instrumented-mdl -x=coverage-mdl.xml^
 --assemblyExcludeFilter=.+\.Tests --assemblyExcludeFilter=AltCover.+
) else (
	"C:\Program Files\dotnet\dotnet.EXE" run^
 --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --configuration %CONFIGURATION% --^
 -i=AdvancedDLSupport.Tests\bin\%OUTPUT_DIR%\netcoreapp2.0 -o=instrumented-adl -x=coverage-adl.xml^
 --assemblyExcludeFilter=.+\.Tests --assemblyExcludeFilter=AltCover.+ --assemblyExcludeFilter=Mono\.DllMap.+

	"C:\Program Files\dotnet\dotnet.EXE" run^
 --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --configuration %CONFIGURATION% --^
 -i=Mono.DllMap.Tests\bin\%OUTPUT_DIR%\netcoreapp2.0 -o=instrumented-mdl -x=coverage-mdl.xml^
 --assemblyExcludeFilter=.+\.Tests --assemblyExcludeFilter=AltCover.+

)
```
but got a `Did you mean to run dotnet SDK commands?` message. 
Any insight into why that might be happening?

**Comment by OwenMcDonnell** [comment]
Sorry, you can disregard the last question. I wrongly assumed the build machine had the x86 dotnet sdk installed.

**Comment by SteveGilham** [comment]
The latest release, [2.0.324](https://www.nuget.org/packages/AltCover/2.0.324) has the changes in the project files to build without having to clear %Platform%; and I've taken the results of working with just the x86 runtime (and not the SDK) on the AppVeyor default build machine, and written them up as [a wiki page](https://github.com/SteveGilham/altcover/wiki/x86-support-for-.net-core).

It boils down to -- if you can get your tests to run without the coverage gathering, then you're good.  It is possible to inject either and x86 or an AnyCPU recording assembly into the system under test by pre-building altcover appropriately then running rather than as a build+run in one step; and whichever you've built should work to drive the coverage collection in runner mode.

**Comment by SteveGilham** [comment]
Assuming the thumbs-up and a quiet week means all is now good.
