### ISSUE TITLE
dotnet test takes 19s, after we do dotnet add package AltCover it takes 1+hour

### ISSUE THREAD

**Issue by amitwats** [SteveGilham/altcover#51]
When we executed a test execution using `dotnet test someProj.csproj` the test execution takes 19 seconds. After we add packages with `dotnet add package AltCover` it takes more than 1 hour. 

1) Is this normal? 
2) Is there a way to minimise this?

**Comment by SteveGilham** [comment]
No, that is not normal.  While there is necessarily some overhead in the coverage gathering, including needing to serialize the output in multi-threaded situations, I've not observed that factor of slowdown myself.

For example, AltCover's own unit tests take 50s by themselves, but that only increases to 2 minutes when self-instrumenting, and that's including build time.

Can you isolate a simple example of the problem that you can share?

**Comment by SteveGilham** [comment]
I have made changes in 5.0.665 which have improved the throughput and speeded unit tests for me; however I've not had such a pathological case to work with, si I don't know if it will make any difference for your case.
