### ISSUE TITLE
Question about p:AltCoverPathFilter

### ISSUE THREAD

**Issue by sberserker** [SteveGilham/altcover#52]
Trying to exclude files by path but can't get it to work:
/p:AltCoverPathFilter=".*FileName\.cs"

Expected result file not being instrumented and excluded completely
But when I apply Path or File filter what i'm seeing is that file still getting instrumented but coverage is 0. 
Please let me know if I need provide more info

**Comment by SteveGilham** [comment]
Source-file information lives at the statement level, so is discovered and applied when each method is processed.  For NCover format, the source lines get marked as `excluded="true"`; OpenCover format doesn't have this, so the XML gets generated with no indication that the method is not instrumented.

That'll be a bug, then.

**Comment by SteveGilham** [comment]
Path filtering for everything but NCover format was variously broken; but should not be fixed in v 5.0.665

**Comment by sberserker** [comment]
Confirming it works now
