### ISSUE TITLE
Question: what command-line args do I pass altcover to ignore failing tests

### ISSUE THREAD

**Issue by neomatrix369** [SteveGilham/altcover#53]
What command-line args do I pass `altcover` to ignore failing tests? This is important as when trying to run a project that has one or more failing tests, the exit code returned is non-zero, while this is correct as there is a failing test, it is something I would like to suppress.

We have in the world of maven or gradle (ignore failing tests switch(es)). 

If this question has been answered, please refer me to the issue.

**Comment by SteveGilham** [comment]
AltCover itself is transparent to whatever it is you are executing.

If you're using AltCover to launch the tests (either through the `-- ...` command line option or `Runner -x [executable] -- [arguments]` option) then assuming that the AltCover code doesn't have problems of its own (including a `--threshold` failure if relevant), the return code will be exactly that returned by the program executed (in the same way that e.g. OpenCover does).  In this case, the problem reduces to coping with the non-zero return code from the tests.

In all other cases, the steps are 

1. altcover (instrumenting)
2. tests
3. altcover (collecting)

and it depends on how this sequence is being orchestrated whether step 2 producing a non-zero return code aborts the sequence, preventing step 3 from executing.  For just this reason, in the `dotnet test` case, I include an override of the default Test target with an error handler that runs step 3 even if step 2 fails.

I could add a flag saying to lose the return code from any process that AltCover launches, if there's an actual use-case for it.

**Comment by SteveGilham** [comment]
I should add that, whatever the return code from a process that AltCover launches, the AltCover program itself executes around it, regardless.  The launched process return code is just passed through to the exit, possibly getting replaced by something (`--threshold` limits, or failure conditions due to I/O errors) from AltCover in the later processing.

**Comment by SteveGilham** [comment]
[Release 5.1.666](https://www.nuget.org/packages/AltCover/5.1.666) adds a "--dropReturnCode" command line option and API equivalents, for both the prepare and the collect/runner stages, so that the return code of any launched process is ignored.

**Comment by neomatrix369** [comment]
@SteveGilham Thanks for this enhancement
