### ISSUE TITLE
Altcover cobertura output xml file corrupt

### ISSUE THREAD

**Issue by TclasenITVT** [SteveGilham/altcover#55]
I have a Dotnet core project that uses xunit + altcover to create test reports and code coverage(cobertura) results. The issue is that the generated xml file seems to be corrupt in some way as the tfs 2018 is unable to publish the code coverage results. I switched to altcover from coverlet. The code coverage reports, also in cobertura format, by coverlet could be published. 
I am using 'altcover' version 5.0.665.
Dotnet core 2.2.
Fsharp.Core 4.6.1
These are my dotnet test parameter: /p:AltCover=true /p:AltCoverCobertura=./cobertura/coverage.cobertura.xml /p:AltCoverAssemblyExcludeFilter=xunit /p:AltCoverForce=true"
I also tried it without the AssemblyExcludeFilter=xunit but it still wasn't successfull. (The runtime increased from 00:00:08.5281807 to 00:02:38.1779466)
This zip contains the coverage.cobertura.xml with xunit excluded.
[coverage.cobertura.xml.zip](https://github.com/SteveGilham/altcover/files/2860324/coverage.cobertura.xml.zip)

**Comment by TclasenITVT** [comment]
Hello Steve I got it  to work with [ReportGenerator](https://github.com/danielpalme/ReportGenerator). In this [comment](https://github.com/Microsoft/azure-pipelines-tasks/issues/9569#issuecomment-467031030) I have linked both xmls maybe that can give you more insights in how to fix this.

**Comment by SteveGilham** [comment]
I finally managed to get some time to look at this; and I'm not clear what problem is being encountered here.

The more recent file you link, `Cobertura.xml` to uses a more recent schema than the AltCover output implicitly uses
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
```
but is not a valid document according to that schema -- the `method` elements lack a `complexity` attribute and they contain `line` elements directly, rather than nested inside a `lines` element.

Considering the xml AltCover is generating, to be properly consistent it should start
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-03.dtd">
```
but it is otherwise fully DTD conformant.

**Comment by SteveGilham** [comment]
[Related issue opened in ReportGenerator](https://github.com/danielpalme/ReportGenerator/issues/219)

**Comment by SteveGilham** [comment]
FWIW coverlet's cobertura ouput is also coverage-04.dtd format except that it omits the DTD and the method complexity attributes; but it does have the `lines` tag containg the individual `line` records under `method` elements.

**Comment by danielpalme** [comment]
New release of ReportGenerator is available:
https://www.nuget.org/packages/ReportGenerator/4.0.15

**Comment by SteveGilham** [comment]
[Release 5.1.666](https://www.nuget.org/packages/AltCover/5.1.666) now outputs in explicit"http://cobertura.sourceforge.net/xml/coverage-04.dtd" compliance (rather than being implicit coverage-04), so I think we can call this resolved at this end.

**Comment by TclasenITVT** [comment]
Thanks @SteveGilham  I will test it asap.

**Comment by TclasenITVT** [comment]
Yes after updating to 5.1.666 the doctype is set like this:

DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd"
