### ISSUE TITLE
Questions about tests failling and coverage thresold

### ISSUE THREAD

**Issue by poumup** [SteveGilham/altcover#58]
Hi,

1st question : Is it possible to failed runner task when tests failed ?

2nd question : Is it possible to define global coverage thresold and failed runner when the coverage is under the thresold ?

**Comment by SteveGilham** [comment]
1) This is already the default behaviour in the supplied process chaining methods

If you are using `altcover Runner -x [test runner] ... -- [test runner arguments], then a failing (non-zero) return code from the executable will be the return code of the `altcover` process unless you explicitly use the `--dropReturnCode` option to ignore the spawned process return code; or unless `altcover Runner` itself fails.

If you are using `dotnet test /p:AltCover="true"`, then the post-processing is done in an `OnError` handler, and the `VSTest` task will still exit with error if the test step fails.  

Any other build scripting is out of my hands, and tracking the test return code is up to the individual author.

2) Yes. Commandline `altcover Runner -t [threshold percentage]`, or in `dotnet test`, use  `/p:AltCoverThreshold="percentage statement coverage required"`; the former returns the shortfall as return code unless some other error code is being reported, the latter results in a task failure.
