### ISSUE TITLE
Attach to running process

### ISSUE THREAD

**Issue by jmecosta** [SteveGilham/altcover#59]
Hi,

Can i do this with altcover? My purpose is to do test impact analysis of ui tests. So the idea is to be able to tell altcover to start/stop recording coverage when i do a action in ui. 

Thanks

**Comment by SteveGilham** [comment]
Yes, as documented here -- https://github.com/SteveGilham/altcover/wiki/Pause%E2%95%B1Resume-and-the-Control-File

There will be in-memory recording until the file is created, but that record is discarded when the control file is created.

**Comment by jmecosta** [comment]
Oh my if this works, this will make our analysis so much accurate. Thanks a
lot for your help :)
