### ISSUE TITLE
Question: generating a report while application is running?

### ISSUE THREAD

**Issue by roozbehid-ic** [SteveGilham/altcover#6]
Is it possible that while application is running I figure out coverage percentage and/or coverage report?

**Comment by SteveGilham** [comment]
Not currently.

As gathering coverage generally involves running mutated binaries, either built that way (e.g. `gcov`, Clover), post-processed like this and the other recent coverage-for-.net core projects, or at assembly load time (like OpenCover or NCover), it's tacitly assumed that the execution will be a test run with some definite beginning, middle and end.

The nearest approximation you can do at the moment is use the `--callContext` argument to timestamp coverage hits, and then after the test run is completed, post-process the XML to extract visits during any interval of interest.

Meanwhile, I can queue up a TODO item to allow more control than the current single bit at the start that says "write to file until done" vs "write to memory, then rewrite the report while the process exits" -- it would need  "start recording", "stop recording", "clear the report" and "save off/merge the current report", I would think.

**Comment by SteveGilham** [comment]
From build 3.0.461-pre (commit f94cb39b) AltCover supports controlling coverage collection to file by manual creation or deletion of the control file during the execution of the instrumented code.  This allows coverage to be started, paused, and resumed as desired, and reports generated separately for each step. 

Somewhat more detail [in the wiki](https://github.com/SteveGilham/altcover/wiki/Pause-Resume-and-the-Control-File).

**Comment by SteveGilham** [comment]
This feature is now available in [release 3.0.466](https://github.com/SteveGilham/altcover/releases/tag/release%2Fv3.0.466).
