### ISSUE TITLE
AltCover sets automatic properties in C# as not coverable

### ISSUE THREAD

**Issue by AlexSala07** [SteveGilham/altcover#61]
I have some functions in my program that use automatic properties. As you can see in my report, these properties are set as not coverable although they should be executable:

![image](https://user-images.githubusercontent.com/51366225/60863802-18ca2700-a222-11e9-8a76-82d72e91079a.png)

I tried the same function using opencover and that's how it should work:
![image](https://user-images.githubusercontent.com/51366225/60863873-41eab780-a222-11e9-891a-7e5bc1bf5894.png)

**Comment by SteveGilham** [comment]
This is by design.  They are not instrumented as they are amenable to static analysis for their correctness, being purely syntactic sugar for field access.  This removes a source of "trivial tests to increase coverage" clutter.
