### ISSUE TITLE
Documentation on -o parameter might be false

### ISSUE THREAD

**Issue by AlexSala07** [SteveGilham/altcover#62]
I used the following command:
`AltCover.exe --save --inplace --single -i=folderInput /o=folderInput\__AltCoverInstr --opencover -x=xmlOutput.xml -- AltCover.exe runner --executable=application.exe -r=folderInput -w=applicationConfigFolder`

As i ran this command, the "__AltCoverInstr" folder got created at the path given to the -o parameter. In the "Usage" section of the Wiki you have written that the -o parameter gets the instrumented assemblies and their companions.

The files in my -o folder are the original, not instrumented files I had, before running the command. The instrumented files in this case, would replace the original ones at the "folderInput" location.
Is there maybe a mistake in the documentation?

P.S. Thank you for your quick and informative responses.

**Comment by SteveGilham** [comment]
See documentation for `--inplace`

* --inplace Optional: Instrument the inputDirectory, rather than the outputDirectory (e.g. for dotnet test)

**Comment by SteveGilham** [comment]
Added cross-reference from the `-o` help-text to the `--inplace` parameter in release 5.3.679
