### ISSUE TITLE
Why does the Crap Score give negative results?

### ISSUE THREAD

**Issue by Paradoxon101** [SteveGilham/altcover#63]
In our code there are 4 methods in which the Crap Score is output extremely nagative.
According to definition this should not happen:
https://testing.googleblog.com/2011/02/this-code-is-crap.html

![image](https://user-images.githubusercontent.com/11892773/61698103-d2ec8300-ad38-11e9-962d-c73ccab979f3.png)

**Comment by SteveGilham** [comment]
The immediate answer is "I'm not sure."  The calculation is all done in floating point double precision, so it's not anything obvious like integer overflow.  

In the case of the second of those methods, a coverage of around 14799.7% would give the observed score, though I'm not sure what string-parsing error might turn a plausible coverage (XML attribute) value into something like that.

In lieu of a complete repro case, could you provide at least the `<Method ` line from the XML report for these methods, like
```
            <Method visited="true" cyclomaticComplexity="10" nPathComplexity="512" sequenceCoverage="71.43" branchCoverage="68.42" crapScore="12.33" isConstructor="false" isStatic="true" isGetter="false" isSetter="false">
```

**Comment by Paradoxon101** [comment]
Of course, here are the values from the XML:

`<Method visited="true" cyclomaticComplexity="23" nPathComplexity="512" sequenceCoverage="86.21" branchCoverage="57.89" isConstructor="false" isStatic="false" isGetter="false" isSetter="false" crapScore="-327285931.52">`

`<Method visited="true" cyclomaticComplexity="24" nPathComplexity="224" sequenceCoverage="69.23" branchCoverage="44.44" isConstructor="false" isStatic="false" isGetter="false" isSetter="false" crapScore="-182956793.53">`

`<Method visited="true" cyclomaticComplexity="17" nPathComplexity="512" sequenceCoverage="71.79" branchCoverage="52.63" isConstructor="false" isStatic="false" isGetter="false" isSetter="false" crapScore="-102521159.12">`

<Method visited="true" cyclomaticComplexity="12" nPathComplexity="512" sequenceCoverage="71.01" branchCoverage="73.68" isConstructor="false" isStatic="true" isGetter="false" isSetter="false" crapScore="-49413159.02">

**Comment by Paradoxon101** [comment]
It looks like the sequenceCoverage is parsed incorrectly:

Complexity | Coverage | CRAP
-- | -- | --
1 | 100 | 1
23 | 8621 | -327285931,5
23 | 86,21 | 24,38722999
16 | 100 | 16

**Comment by SteveGilham** [comment]
There's a tentative fix at https://ci.appveyor.com/project/SteveGilham/altcover/builds/26207261/artifacts ([direct .nupkg link](https://ci.appveyor.com/api/buildjobs/6ev752vedv36wvxp/artifacts/_Packaging%2Faltcover.5.3.677-pre.nupkg) here).  It's tentative because all the experiments with localized decimal marks I've tried all ended up with zero as the coverage value, rather than eliding the symbol.

**Comment by SteveGilham** [comment]
@Paradoxon101 -- have you had the opportunity to try this new build?  If so, did it remedy the problem?

**Comment by SteveGilham** [comment]
This change is incorporated in release 5.3.679, if that is more convenient for you.

**Comment by SteveGilham** [comment]
@Paradoxon101 This change is incorporated in release 5.3.679, if that is more convenient for you.

**Comment by wn11** [comment]
Thank you for the fix, the Crap Score now seems to be correct.

**Comment by Paradoxon101** [comment]
Thanks, now it fits!
