### ISSUE TITLE
How to only include assemblies from namespace A or B

### ISSUE THREAD

**Issue by cbroxton** [SteveGilham/altcover#67]
Hey @SteveGilham,

We have a scenario where we are running dotnet test as part of our Azure Devops pipeline on multiple test projects. I would like to be able to tell AltCover to exclude all assemblies that aren't i.e. NamespaceA.* OR NamespaceB.* however I'm unsure how to do this as | is a special character.

I'm attempting to run a command like this...

`dotnet test /p:AltCover=true /p:AltCoverCobertura="Cobertura.xml" /p:AltCoverAssemblyExcludeFilter='^(?!(NamespaceA|NamespaceB)).*$'`

However AltCover treats this as two separate exclusions because of the | character I believe and I get the following error...

`C:\...\...\AltCover.targets(39,5): error : parsing 'NamespaceB)).*$' - Too many )'s. [C:\...\...\Test\Test.csproj]
C:\...\...\AltCover.targets(39,5): error : parsing '^(?!(NamespaceA' - Not enough )'s. [C:\...\...\Test\Test.csproj]`

Is there any way I can perhaps escape the | character, or a different way to write my exclusion?

**Comment by SteveGilham** [comment]
Short of making an edit to the altcover.targets file to change/remove the pipe from the "this pattern|that pattern" role as part of your build process, I can't see an obvious work around at this point.

Look for an update this weekend to formalize that approach (choose your own separator).

**Comment by SteveGilham** [comment]
Addressed in release v6.0.700 -- escape the `|` in the regex by doubling it, as in
```
/p:AltCoverAssemblyExcludeFilter='^(?!(NamespaceA||NamespaceB)).*$'
```

**Comment by cbroxton** [comment]
@SteveGilham That sounds perfect, thanks very much I'll have a play with it when I'm back at work

**Comment by cbroxton** [comment]
Hey @SteveGilham,

Yep that's working great thanks, I just have an unrelated question. Is it right that classes which only have properties with default getters/setters are always excluded from the code coverage results? For example the below class.

public class MySimpleClass {
    public int Foo { get; set; }
    public string Bar { get; set; }
}

**Comment by SteveGilham** [comment]
This is by design, to avoid the temptation to clutter projects with trivial tests "just to get coverage".  

Auto-properties are just field accesses, which makes them simple to detect (and ignore).  They're better suited to static analysis -- "is it used?"  "is this the right one to use here?" -- than for unit or system tests.

**Comment by cbroxton** [comment]
Yep, I agree, just wanted to check that was intended behaviour, thanks :)
