### ISSUE TITLE
Altcover does not instrument all projects in solution

### ISSUE THREAD

**Issue by gellweiler** [SteveGilham/altcover#69]
I have a solution that contains multiple projects (Applications and libs) and one test project that references all other projects. When I run  altcover I expect it to report coverage for all projects, however only a few projects are covered.

I'm using mono on Linux and OS X.

These are the projects that I have in my solution:
- BeatsWrapper (Application)
- BeatsWrapper.AppSettingsConfigParser (lib)
- BeatsWrapper.ConfigUpdater (Application)
- BeatsWrapper.SystemWrapper (lib)

I run altcover:
```
$ mono packages/altcover.*/tools/*/AltCover.exe -i BeatsWrapper.Tests/bin/Release -o "$(pwd)/__Instrumented"
Instrumenting files from /Users/d0265672/src/beatswrapper/BeatsWrapper.Tests/bin/Release
Writing files to /Users/d0265672/src/beatswrapper/__Instrumented
   => /Users/d0265672/src/beatswrapper/BeatsWrapper.Tests/bin/Release/BeatsWrapper.exe
   => /Users/d0265672/src/beatswrapper/BeatsWrapper.Tests/bin/Release/BeatsWrapper.SystemWrapper.dll
   => /Users/d0265672/src/beatswrapper/BeatsWrapper.Tests/bin/Release/BeatsWrapper.Tests.dll
   => /Users/d0265672/src/beatswrapper/BeatsWrapper.Tests/bin/Release/nunit.framework.dll

Coverage Report: /Users/d0265672/src/beatswrapper/coverage.xml


    /Users/d0265672/src/beatswrapper/__Instrumented/nunit.framework.dll
                <=  nunit.framework, Version=3.12.0.0, Culture=neutral, PublicKeyToken=null
    /Users/d0265672/src/beatswrapper/__Instrumented/BeatsWrapper.SystemWrapper.dll
                <=  BeatsWrapper.SystemWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    /Users/d0265672/src/beatswrapper/__Instrumented/BeatsWrapper.exe
                <=  BeatsWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    /Users/d0265672/src/beatswrapper/__Instrumented/BeatsWrapper.Tests.dll
                <=  BeatsWrapper.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```
I then generate tests with `mono packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe __Instrumented/BeatsWrapper.Tests.dll`

It generates a report with coverage for BeatsWrapper, BeatsWrapper.Test and BeatsWrapper.SystemWrapper and nunit internals but not for BeatsWrapper.AppSettingsConfigParser and BeatsWrapper.ConfigUpdater.

The test code definitley calls code of all projects.

Do you have any idea why BeatsWrapper.AppSettingsConfigParser.dll and BeatsWrapper.ConfigUpdater.exe don't get instrumented by altcover?

**Comment by gellweiler** [comment]
OK I think I found out what is going wrong. When I instrument Debug instead of release, everything works as expected. So I assume it has to do with debug symbols.

**Comment by SteveGilham** [comment]
That's correct -- debug symbols are the key to translating between IL instructions and the source code; so they are a requirement for any coverage tool that applies itself after compilation is done.  

Compile-time coverage instrumentation (e.g. gcc --coverage for gcov) finesses the issue by injecting equivalent information into the build output, just in a different format from plain debug information.
