### ISSUE TITLE
Creating a simple experience

### ISSUE THREAD

**Issue by TheAngryByrd** [SteveGilham/altcover#7]
The experience coverlet brings is pretty nice by being able to just add an msbuild target. https://github.com/tonerdo/coverlet/blob/master/src/coverlet.msbuild/coverlet.msbuild.targets

Since this project can handle full/mono/core, I think its worth investing here.  Do you think it's possible to add something similar instead of doing this https://github.com/haf/expecto/issues/219#issuecomment-374810994 ?

**Comment by SteveGilham** [comment]
Added to the TODO list.  Once the current in-progress is done, the engine will be down to corner cases, anyway.

**Comment by SteveGilham** [comment]
Closing after satisfactory reception
