### ISSUE TITLE
Question re: Instrumenting a background process

### ISSUE THREAD

**Issue by parekhkb** [SteveGilham/altcover#70]
My Integration test suite sets up a TestServer in process, but also launches a separate process for a background worker. Using OpenCover or DotCover on windows, I am able to collect coverage from the background worker without any extra instrumentation or setup. But on Linux/Mac I haven't found a tool that can do that out of the box.

I am trying to get AltCover to do it, but having some issues. Can I ask for advice on what I might be doing wrong. The documentation is not clear in this case.

Here is my setup:

Test project has the following MsBuild code to publish a local copy of the background worker
```XML
  <Target Name="PublishWorker" AfterTargets="Build">
    <PropertyGroup>
      <BackgroundServerPublishDir>$(MSBuildProjectDirectory)\$(OutputPath)\Worker\</BackgroundServerPublishDir>
    </PropertyGroup>
    <Message Text="Publishing BackgroundJob Server for Integration Tests">
    </Message>
    <MSBuild Targets="Publish" Properties="Configuration=$(Configuration);PublishDir=$(BackgroundServerPublishDir);NoBuild=true;BuildProjectReferences=false" StopOnFirstFailure="true" Projects="..\..\..\src\Worker\Server\MyApp.Worker.Server.csproj" />
  </Target>
```

Then my Test Setup class does the following:
```
var proc = new Process
{
    StartInfo =
    {
        FileName = "dotnet",
        Arguments = Path.Combine(workingDir, targetDll),
        WorkingDirectory = workingDir,
        CreateNoWindow = true,
        RedirectStandardOutput = true,
        RedirectStandardError = true
    }
};

proc.Start();
```

I have verified we are gracefully shutting down this process on completion. In Linux we use SigInt, but on mac and windows we write a file to disk which signals a graceful shutdown.

Stack:
Runner: xUnit.net (via `dotnet test`)
Framework: .NET Core 2.2
Merge tool: Report Generator dotnet core global tool

I tried the following 4 steps, but am still not seeing any coverage for the background worker. When I run these same tests with OpenCover.exe or DotCover.exe on windows, it works as expected even without extra instrumentation steps.

1. Before Run: 
```
altcover --save --inplace -i ./test/IntegrationTests/IntegrationTests.Test/bin/Debug/netcoreapp2.2/Worker -e '^(?=(MyApp\..*Test.*)).*$|^(?!(MyApp)).*$'
```
2. Test Run:
```
dotnet test /p:AltCover=true /p:AltCoverForce=true /p:AltCoverAssemblyExcludeFilter='^(?=(MyApp\..*Test.*)).*$|^(?!(MyApp)).*$'
```
3. After Run:
```
altcover runner --collect -r ./test/IntegrationTests/IntegrationTests.Test/bin/Debug/netcoreapp2.2/Worker
```
4. Merge
```
reportgenerator -reports:test/**/coverage.xml -targetdir:./reports
```
Thanks in advance for any help.

**Comment by SteveGilham** [comment]
If your test set-up really is just a process launcher, containing nothing of interest, and what you really want is to watch`Worker.dll`, then step 2 can simply be 
```
dotnet ./test/IntegrationTests/IntegrationTests.Test/bin/Debug/netcoreapp2.2/Worker/Worker.dll
```
In fact, depending on the working directpries, it is possible that the `dotnet test` step is actively frustrating your intent by creating `coverage.xml` that overwrites the one created in stage 1.

**Comment by SteveGilham** [comment]
Also, steps 2 and 3 can be safely merged as 
```
altcover runner -r ./test/IntegrationTests/IntegrationTests.Test/bin/Debug/netcoreapp2.2/Worker -x dotnet --  ./test/IntegrationTests/IntegrationTests.Test/bin/Debug/netcoreapp2.2/Worker/Worker.dll
```
with AltCover in runner mode being the process launcher for the instrumented code; it will wait for the process it launches to terminate before reporting the coverage data.

**Comment by SteveGilham** [comment]
Having slept on this, I realise that I misunderstood the detail what you were doing here.  

I'm used to server operational/integration testing happing with a separate test script driving the client, and the test infrastructure handling the synchronizing at a higher level; but you're having the `dotnet test` session drive both client and server, and handle the synchronization so the client (the tests) doesn't start running until the server (worker process) has stabilized, and that the server doesn't stop until the tests have.

So forget much of what I wrote yesterday.

What you are doing ought to work (i.e. launching the server, and then running the tests from the client), so long as everything joins up OK (`workingDir` evaluates to `the place where the instrumented worker lives, and the like).

So what I now need to ask is
* are you getting two distinct `coverage.xml` files?
* did you mean that the worker report be in NCover format? (no `--opencover` argument)
* do the reports contain the the expected `<Module>` (OpenCover) or `<module>` (NCover) entries

---

The filter regex, which looks like you're trying to exclude everything that's not yours looks plausible.  After a little touch-testing, it seems to do what looks like would be wanted -- letting through anything starting `MyApp.` except those with `Test` later in the name.  This could, however, be simplified with the `--localSource`  (`/p:AltCoverLocalSource=true`) feature of the  v6.1.708 release, switching off all third party libraries with debug symbols, so likely just needing to have `-e Test`.

Fortunately, the fact that
```
/p:AltCoverAssemblyExcludeFilter='^(?=(MyApp\..*Test.*)).*$|^(?!(MyApp)).*$'
```
which actually maps to the two separate command line arguments
```
-e '^(?=(MyApp\..*Test.*)).*$' -e'^(?!(MyApp)).*$'
```
has the same effect as
```
-e '^(?=(MyApp\..*Test.*)).*$|^(?!(MyApp)).*$'
```
being true (excluding) if either half is true.

**Comment by parekhkb** [comment]
You are correct, we are using an xunit.net Fixture to setup multiple TestServers and the background worker. 

here are the answers to your questions:
- are you getting two distinct coverage.xml files? 
No, I am not seeing any coverage file in the Worker directory
- did you mean that the worker report be in NCover format? (no --opencover argument)
This was not intentional. I thought OpenCover was the default.
- do the reports contain the the expected <Module> (OpenCover) or <module> (NCover) entries
I see <module>

Also your suggestion to use /p:AltCoverLocalSource=true does not seem to work for me. I see instrumentation attempted for all the xunit.runner dlls. 

After some refactoring I was able to solve my issue by switching the worker to be launched as a thread instead of a seperate process.:

```
            _worker = Task.Factory
                          .StartNew(() => Worker.Server.Program.RunAsync(_cancellationTokenSource.Token),
                                    _cancellationTokenSource.Token,
                                    TaskCreationOptions.LongRunning,
                                    TaskScheduler.Default)
                          .Unwrap();
```


This unblocked me, but doesn't explain why I wasn't able to collect coverage for the worker as a process.

**Comment by SteveGilham** [comment]
* No, I am not seeing any coverage file in the Worker directory
The default report file location for the command-line tool is `coverage.xml` in the current working directory; so Step 1 will be creating a file in the `.` of `./test/IntegrationTests/IntegrationTests.Test/bin/Debug/netcoreapp2.2/Worker`

It would take an explicit `-x ./test/IntegrationTests/IntegrationTests.Test/bin/Debug/netcoreapp2.2/Worker/coverage.xml` to place the coverage file in that directory.

Note -- difference in behaviour `dotnet test` puts the coverage file relative to the directory containing the project being run.

* This was not intentional. I thought OpenCover was the default.
This is the usual story -- it's that way for historical reasons.  The AltCover project started back in 2010, before OpenCover was a thing, and generated NCover format to replace the freeware tool that stopped working with .net 4.0. When I added support for OpenCover format last year, I left NCover as the command-line default for backward compatibility, but made OpenCover the default for newer features like `dotnet test`.

If you've found a coverage file with lowercase `<module>` entries, that would be the result of instrumenting the worker, and you can check which assemblies it has found.

---
> This unblocked me, but doesn't explain why I wasn't able to collect coverage for the worker as a process.

Once the code is instrumented (as in step 1), then when it executes it will make calls to record coverage so long as [the `.acv` control file](https://github.com/SteveGilham/altcover/wiki/Pause%E2%95%B1Resume-and-the-Control-File) is present, and until it is replaced.

That's another possibility -- if the `dotnet test` causes a rebuild of the worker, then the in-place instrumented code would be overwritten.  Perhaps try `dotnet test --nobuild` in step 2.

**Comment by SteveGilham** [comment]
Here's a simple self-contained example of the thing you are trying to do
[Echo.zip](https://github.com/SteveGilham/altcover/files/3590410/Echo.zip); it has a simple TCP one-shot echo server for the worker, and the test sends a string and tests that it gets echoed.

Unzip, and run demo.bat

I've also [checked it into the demo folder in the AltCover repo](https://github.com/SteveGilham/altcover/commit/4620e40c09e881df0f656fd4c6eef07c594e1136).

**Comment by SteveGilham** [comment]
Is this issue still live?

**Comment by parekhkb** [comment]
I've unblocked myself by using a Task instead of a background process.
Likely the issue is with my own understanding.

**Comment by SteveGilham** [comment]
Re-open if you need.
