### ISSUE TITLE
Is there any way to limit the collecting items?

### ISSUE THREAD

**Issue by 0xaryan** [SteveGilham/altcover#79]
I'm running altcover on a pretty huge project with a lot of assemblies. It produces a 600MB template file with a lot of details. Is there any way to customize the collection process, like only collecting the name of the visited files, or methods?

**Comment by SteveGilham** [comment]
That is huge -- that report file size is an order of magnitude larger than any emitted by a single component (distinct solution file) I encountered in my wagie days in enterprise software.

Currently, the best granularity you can get is via excluding assemblies from coverage and partitioning the tests by sub-components to get multiple, but more manageable, reports.

The up-front report template is what stores the mapping from the internally numbered code point to the code that it represents, so the test run only needs to record "I was at this point", and the after-run processing simply fills in visit counts and computes any derived quantities, so the full data would still end up as that 600MB+ monolith.

I can see a couple of ways forwards, though --
Add a "summary" mode that only records method entry ans also omits things like the compiler generated classes associated with lambdas or the like, and lose all the finer grained information
Add an option to write the initial XML file in compressed form, only expanding it on completion, with the proviso that this would not be compatible with "classic" mode (which can perform multiple update passes to increment the visit counts)

**Comment by SteveGilham** [comment]
As well as the existing filter options (`--assemblyExcludeFilter`, `--assemblyFilter`, `--fileFilter` and `--pathFilter`), the 7.0 release will have `--zipfile` which puts the XML report into an archive, and `--methodpoint` which will only record method entry visits.

**Comment by 0xaryan** [comment]
That's awesome.

**Comment by SteveGilham** [comment]
These features are in the new [7.0.766-pre release](https://www.nuget.org/packages/AltCover/7.0.766-pre).

There should not be any functional changes before a full 7.0 release; the pre-release is just to ensure I'm happy with the adjusted names in the API before freezing it for 7.x, which is an orthogonal issue to the new command-line features.

**Comment by SteveGilham** [comment]
Full 7.0 release now available

**Comment by SteveGilham** [comment]
Assuming that no news is good news.
