### ISSUE TITLE
Build instructions don't work.

### ISSUE THREAD

**Issue by lucaregini** [SteveGilham/altcover#8]
Hi,
I have tried to build the solution from a clean machine VM with the latest version of VS 2017.
The solution doesn't build and it's very difficult to understand the root cause for somebody that doesn't have F# specific experience.
The restore command installs FSharp.Core 4.3.4. as first thing however it's unclear whether this is the source of error. If this is the case then I believe that the bootstrap instructions should be made more explicit by adding the necessary instructions for installing FSharp.Core 2.3.0.0.
I attache here the logs of the restore, fake run setup and fake run build commands.
[restore.log.txt](https://github.com/SteveGilham/altcover/files/1894663/restore.log.txt)
[fake run setup.txt](https://github.com/SteveGilham/altcover/files/1894665/fake.run.setup.txt)
[fake run build.txt](https://github.com/SteveGilham/altcover/files/1894666/fake.run.build.txt)

**Comment by SteveGilham** [comment]
The F# 4.3.4 NuGet package is used purely as a convenience for Mono/Linux builds.

The build works with an out-of-the-box AppVeyor build machine with the Visual Studio 2017 profile, so checking [what's actually in the box](https://www.appveyor.com/docs/build-environment/#pre-installed-software), I realise that it also comes with [Visual F# Tools 4.0 RTM](https://www.microsoft.com/en-us/download/details.aspx?id=48179), as well as, presumably, both the F# components checked in the VS2017 install.

That may well be the missing ingredient I'd not previously noticed.

**Comment by SteveGilham** [comment]
Having recently repaved one of my old machines I took the opportunity to install the Visual F# Tools 4.0 RTM, and it installs the necessary .net 2.0 support under C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\

I've updated/overhauled the build section of README.md as a result.

**Comment by lucaregini** [comment]
Still not working. I have installed  the "Visual F# Tools 4.0 RTM" package but I am still getting errors. Attaching the full build log starting with the git clone and going trought the restore/setup/build cycle.
Please note that this is the same VM that I used to run the previous build attempt.
[fullbuildlog.txt](https://github.com/SteveGilham/altcover/files/1907293/fullbuildlog.txt)

**Comment by SteveGilham** [comment]
So, it's failed while running [FSharpLint](https://github.com/fsprojects/FSharpLint/) over the code; I have seen intermittent failures from that package before now.  What happens when you try again?

**Comment by SteveGilham** [comment]
What you are seeing looks like [FSharpLint issue 250](https://github.com/fsprojects/FSharpLint/issues/250), only not in a .net core context.

**Comment by lucaregini** [comment]
It's sistematic with 100% occurence rate. It should be easy to reproduce: I am using a DS1 Azure Lab instance ( 1 CPU, 3,5 Gb of RAM ) with the latest VS 2017 and Visual F# Tools 4.0 RTM. Could you please document also this error and how to address it ( for example by removing the FS#Lint target )?

**Comment by SteveGilham** [comment]
Pull requests will be accepted.

**Comment by SteveGilham** [comment]
I have made a speculative change to address the issue in [commit 94beb84ba6](https://github.com/SteveGilham/altcover/commit/06adec1d077d8020a45417893eb71ee796dc736e); if that doesn't resolve the issue directly, then setting 
```
$env:FSharpLintEnabled="false"
```
should suppress that step

**Comment by lucaregini** [comment]
Confirmed that it works by excluding the FSLint step. I am closing the issue. 
P.S: I would like to contribute to the project what is there to be done and how to get in touch?

**Comment by lucaregini** [comment]
New issue after downloading latest master. Build log attached
[buildlog newissue.txt](https://github.com/SteveGilham/altcover/files/1921407/buildlog.newissue.txt)

**Comment by SteveGilham** [comment]
A new Fake RC came out with another breaking API change.  The fix is in the feature/staging branch, just not yet in master.

**Comment by SteveGilham** [comment]
Merged into master.
