### ISSUE TITLE
Add a treshold check for maxCrapScore

### ISSUE THREAD

**Issue by OnurGumus** [SteveGilham/altcover#80]
I personally find Crap score better than code coverage, so I think it could be useful to add a fail threshold constraint for maxCrapScore. Also maxCyclomaticComplexity might be good too.

**Comment by SteveGilham** [comment]
Max complexity by itself is a static-analysis measure,so that would really be a logically separate step.  For that, I would recommend using the fork I've built of the old Mono.Gendarme analyzer, which is available as [a dotnet global tool](https://www.nuget.org/packages/altcode.gendarme-tool) -- the `Gendarme.Rules.Maintainability.AvoidComplexMethodsRule` has a configurable threshold via the `rules.xml` file.

CRAP score is based on test coverage, so that would be a valid use-case for AltCover.

**Comment by SteveGilham** [comment]
The 7.0 release will extend the --threshold parameter from just the numeric sequence point percentage to also include branch and method coverage thresholds and maximum CRAP score (1-255).

**Comment by SteveGilham** [comment]
The enhance threshold options are in the new [7.0.766-pre release](https://www.nuget.org/packages/AltCover/7.0.766-pre).

There should not be any functional changes before a full 7.0 release; the pre-release is just to ensure I'm happy with the adjusted names in the API before freezing it for 7.x, which is an orthogonal issue to the new command-line features.

**Comment by SteveGilham** [comment]
Full 7.0 release now available

**Comment by SteveGilham** [comment]
Assuming that no news is good news.

**Comment by OnurGumus** [comment]
It works for me so far.

**Comment by OnurGumus** [comment]
@SteveGilham I don't have an isolated case yet but it seems the threshold score becomes higher than the actual crap score. I have seen it complains that the crap score should be higher even if I set it to 255 which is the max. There is something wrong with the calculation of the threshold.

**Comment by SteveGilham** [comment]
I have a local repro (or at least something looking very similar).  Re-opening issue.

**Comment by SteveGilham** [comment]
The case I have is like this -- ReportGenerator gives one warning, with a CRAP score of 10, for the system under; but putting `-t C15` fails the build, with 
```
Maximum CRAP score achieved is 15 above the threshold of 15.
```
The function with the high CRAP score of 30 is one with no sequence points, cyclomatic complexity of 5, but which is visited.

So, this case, at least, is one where the scoring is not being done correctly in the degenerate case.

I'm interested to see what your example looks like.

**Comment by OnurGumus** [comment]
Unfortunately I can't provide an isolated case right now.

**Comment by SteveGilham** [comment]
What I'm seeing with the as-release code to date is, in the XML report, methods with no sequence or branch points, that have a method point with `vc` > 0 but the method is still flagged as `visited="false"`, and thus has a CRAP score based on zero coverage.  Having fixed issue #84 to ensure the scores are computed everywhere, I now have to fix the visited state too.

**Comment by SteveGilham** [comment]
If you have an XML report from a run showing the problem, the following PowerShell fragments will point out where the high scores are
```
$x = [xml](Get-Content "<path to the report>")

## gets the scores in order
$x.CoverageSession.Modules.Module.Classes.Class.Methods.Method | % { [int] $_.crapScore } | Sort-object

## gets the methods that are above the threshold (just fill in the value)
$x.CoverageSession.Modules.Module.Classes.Class.Methods.Method | ? { ([int] $_.crapScore) -gt <desired threshold> } | % { $_.Parent.Parent }
```
which will allow us to determine whether we are both seeing the same thing (problem coming from methods with no sequence points)

**Comment by OnurGumus** [comment]
How about if you release a pre-release nuget package and I can happily test it for you?

**Comment by SteveGilham** [comment]
Current build [here](https://ci.appveyor.com/project/SteveGilham/altcover/builds/33657950/artifacts)
* Fixes CRAP scores of visited methods with 0 sequence points
* Excludes same from the roll-up in the same way as they are excluded in the OpnCover format for method visited counts

**Comment by OnurGumus** [comment]
Thanks, with latest release I can see it is consistent now. You may close the issue.

**Comment by SteveGilham** [comment]
That change, and a few related features are in formal release [7.1.776](https://www.nuget.org/packages/AltCover/7.1.776)
