### ISSUE TITLE
How do I use altcover.visualizer ?

### ISSUE THREAD

**Issue by dexc99** [SteveGilham/altcover#81]
Are there any instructions on how to use altcover.visualizer ?

I've installed it as a global dotnet tool, but typing altcover.visualizer at a cmd prompt doesn't do anything.
Should I be doing something else ?

**Comment by SteveGilham** [comment]
In its current incarnation, having GTK+3 installed on your machine and in your PATH is a pre-req.  For Windows, this requires jumping through a few hoops, see e.g. https://github.com/GtkSharp/GtkSharp/wiki/Installing-Gtk-on-Windows 

Also, GTK+ needs the GSETTINGS_SCHEMA_DIR environment variable set.  

If that variable isn't set by your install, then you can make it a part of the process-level environment, by command-line argument `--schemadir=path-of-schema-directory` -- that value will be saved into the application configuration for later uses.  For GTK+ installed as above on a vanilla 64-bit system, the appropriate path is `C:\msys64\mingw64\share\glib-2.0\schemas`

That latter bit definitely needs to get hauled out of the 6.7.750 release notes and put somewhere more prominent.

**Comment by SteveGilham** [comment]
Note added to FAQ

**Comment by dexc99** [comment]
Thanks, I’ll give it a go.

**Comment by SteveGilham** [comment]
No news is assumed to be good news after 3 weeks.

**Comment by dexc99** [comment]
Sorry, yeah that worked a treat for me on my personal machine. I didn’t have the required permissions to set it up on my work one unfortunately. 
Thanks for your help with it Steve

**Comment by SteveGilham** [comment]
I've now rewritten the global tool visualizer to use the cross-platform  [AvaloniaUI](http://avaloniaui.net/) toolkit rather than GTK3, which should now make it self-contained.  The new model [v7.1.780](https://www.nuget.org/packages/altcover.visualizer/7.1.780) may solve the issues you were having by simply side-stepping them.
