### ISSUE TITLE
Crap Score 0 on all methods

### ISSUE THREAD

**Issue by bgurmendi** [SteveGilham/altcover#83]
Im geting 0 score on Crap metric. 

![image](https://user-images.githubusercontent.com/1327625/83528395-58a89580-a4e9-11ea-88b2-07f62baa1056.png)

I use this command:
`mono AltCover.exe /i=Test/bin/Debug /outputDirectory=Test/bin/Coverage --localSource`

Mono  version:
`Mono JIT compiler version 5.18.1.28 `

**Comment by SteveGilham** [comment]
Given that instrumentation step, and no mention of following up with any `mono AltCover.exe Runner...`, the next step in your process presumably is running the instrumented code with the coverage being written to the report in the (time limited) end-of-process handler. ([Instrument now, test later](https://github.com/SteveGilham/altcover/wiki/Modes-of-Operation#instrument-now-test-later-classic-mode) style).

In that case, this is expected; the post-processing stage which fills in the CRAP score and other summary data is not run during process termination, so as to make most time available for actually recording the visit data.

To fill in the derived data, like CRAP score, visited percentages and the like, after the fact, there is the PowerShell cmdlet `Write-OpenCoverDerivedState`; alternatively, gather coverage under AltCover in "runner" mode -- either [run the instrumented code from AltCover](https://github.com/SteveGilham/altcover/wiki/Modes-of-Operation#instrument-now-test-later-runner-mode), or [instrument with the `--save` flag, run the tests, then use  `AltCover runner --collect`](https://github.com/SteveGilham/altcover/wiki/Modes-of-Operation#instrument-now-test-later-collect-coverage-after-that) to pull everything into place.

**Comment by SteveGilham** [comment]
I've amended the wiki page to add the word "basic"

> only a subset of OpenCover format (sufficient for basic use with coveralls.io and ReportGenerator) is produced

and added a FAQ item

**Comment by bgurmendi** [comment]
Thanks!!! now calculates CRAP metric

Full comands:
```
mono external_bin/altcover.7.0.770/AltCover.exe /i=Test/bin/Debug /outputDirectory=Test/bin/Coverage --localSource --xmlReport=local_data/coverage/coverage.$filtro_namespace.xml --save
mono --debug --runtime=v4.0 packages/NUnit.Runners.2.6.4/tools/nunit-console.exe -nologo -output=local_data/nunit/out.txt -err=local_data/nunit/err.txt Test/bin/Coverage/Test.dll -run:$filtro_namespace
mono external_bin/altcover.7.0.770/AltCover.exe runner --collect -r Test/bin/Coverage
mono external_bin/ReportGenerator.4.6.0/ReportGenerator.exe  -reports:local_data/coverage/coverage.$filtro_namespace.xml "-targetdir:local_data/coverage/$filtro_namespace" -assemblyfilters:+web  "-filefilters:+/srv/goi/dev/web/$filtro/*;-*.g.cs"  "-historydir:local_data/coverage_hist/$filtro_namespace" -tag:
```
