### ISSUE TITLE
Crap Score not calculated when coverage is 0

### ISSUE THREAD

**Issue by bgurmendi** [SteveGilham/altcover#84]
![image](https://user-images.githubusercontent.com/1327625/83540721-f788be00-a4f8-11ea-99c0-cdf93de26932.png)

Acording to Crap Score formula, when cyclomatic complexity is 4 (first row) and no coverrage then Crap Sore should be 5. 

In the screen capture we can see that when coverage is 0% no Crap Score is calculated.

Im using altcover version 7.0.770

**Comment by SteveGilham** [comment]
Yep. it's a bug.  It's been there since I added the feature, putting it in an "update the visited methods" path.  New release soon.

**Comment by bgurmendi** [comment]
You are very fast!

**Comment by SteveGilham** [comment]
Should be fixed in [release 7.0.773](https://www.nuget.org/packages/AltCover/7.0.773)

**Comment by SteveGilham** [comment]
Assuming that no news is good news.
