### ISSUE TITLE
Does AltCover work with .NET Framework (v4.7.2) and NUnit v2

### ISSUE THREAD

**Issue by sixeyes** [SteveGilham/altcover#88]
The examples are out of date. It shows --opencover which isn't an option in the current release.

So far I've spent several hours and I've got everything working, except getting any code coverage in the report.

 ..\..\AltCover\AltCover.exe -a ExcludeFromCodeCoverageAttribute -i Demo.Test.Unit\bin\Debug -l -o Demo.Test.Unit\bin\Debug\AltCover -x CoverUnit.xml

..\..\AltCover\AltCover.exe Runner -r Demo.Test.Unit\bin\Debug\AltCover -x ..\..\NUnit\2.6.4\bin\nunit-console.exe -w . -- Demo.Test.Unit\bin\debug\Demo.Test.Unit.dll

When I run these two commands it Instruments the files and runs my unit tests

NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.
Runtime Environment -
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.9151 ( Net 3.5 )
ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
..........................................................................
Tests run: 74, Errors: 0, Failures: 0, Inconclusive: 0, Time: 1.2895353 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
A total of 0 visits recorded
Coverage statistics flushing took 0.06 seconds
Visited Classes 0 of 14 (0)
Visited Methods 0 of 24 (0)
Visited Points 0 of 114 (0)
Visited Branches 0 of 52 (0)
Maximum CRAP score 272
==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 0 of 15 (0)
Alternative Visited Methods 0 of 39 (0)
Alternative maximum CRAP score 272

It's just not picking up the code coverage.

Is this configuration not supported or am I missing an option?

**Comment by SteveGilham** [comment]
For that setup as quoted,
```
....\AltCover\AltCover.exe -a ExcludeFromCodeCoverageAttribute -i Demo.Test.Unit\bin\Debug -l -o Demo.Test.Unit\bin\Debug\AltCover -x CoverUnit.xml
```
puts the instrumented code in `Demo.Test.Unit\bin\Debug\AltCover`, while
```
....\AltCover\AltCover.exe Runner -r Demo.Test.Unit\bin\Debug\AltCover -x ....\NUnit\2.6.4\bin\nunit-console.exe -w . -- Demo.Test.Unit\bin\debug\Demo.Test.Unit.dll
```
is running the tests on the untouched assemblies in the original location.

Either instrument with `--inplace`, saving off the original assemblies to the `-o` directory and testing the instrumented assemblies in the original location; or instrument as is and run the tests against the instrumented assemblies as
```
....\AltCover\AltCover.exe Runner -r Demo.Test.Unit\bin\Debug\AltCover -x ....\NUnit\2.6.4\bin\nunit-console.exe -w . -- Demo.Test.Unit\bin\debug\AltCover\Demo.Test.Unit.dll
```
---
The wiki examples should now be fixed.  I knew I was bound to have missed something in the great v7.0 reorganization.

**Comment by sixeyes** [comment]
Thanks for that.

It makes sense. Working as expected.
