### ISSUE TITLE
How to cover just a namespace

### ISSUE THREAD

**Issue by sixeyes** [SteveGilham/altcover#89]
In OpenCover there's a -filter option which is inclusive but AltCover options seem to be exclusive.

The exclusive model makes for long command lines but doing the same for namespaces would be impractical as namespaces are added all the time.

If I only run a namespace when running the NUnit tests, how do I filter the results to only include the namespace?

**Comment by SteveGilham** [comment]
If you want to include types in `A.Certain.Namespace` then as type filter  either

* negative lookahead voodoo `^(?!A\.Certain\.Namespace\.).*$`, or
* [as per the FAQ](https://github.com/SteveGilham/altcover/wiki/FAQ), from release 6.2.714 use the cheat code `?^A\.Certain\.Namespace\.` (if there are no `Bogus.A.Certain.Namespace` types, then the leading `^` won't be needed).

If you also need to exclude inner namespaces, it's best to add a separate type filter entry `A\.Certain\.Namespace\.InnerNamespace\.` for each one explicitly, to avoid filtering out nested types (both explicit and compiler generated) that would be expected to be covered.

**Comment by sixeyes** [comment]
Thanks.

Glad you added the ? option.
