### ISSUE TITLE
E2E coverage

### ISSUE THREAD

**Issue by nripendra** [SteveGilham/altcover#92]
I am trying to get coverage report for E2E tests. I'm looking at [the global altcover in "Instrument now, test later, runner mode"
](https://github.com/SteveGilham/altcover/wiki/Examples-of-use#using-the-global-altcover-in-instrument-now-test-later-runner-mode). Is it possible for altcover to start dotnet core dll without the `test` command?

What I'm looking for is following steps:
- instrument with altcover
- start the dotnet core application with altcover runner.
- Run my E2E (cypress) tests.
- collect the altcover report.

As you can see, my E2E tests are cypress tests and not normal dotnet unit test, and it follows micro-service architecture. So, I need report from multiple services. Is it possible for altcover to collect report from assemblies running in different folders at once?

**Comment by SteveGilham** [comment]
> Is it possible for altcover to collect report from assemblies running in different folders at once?

Yes -- the `--inputDirectory` parameter can be specified many times.  While this was originally provided to allow an NUnit command to refer to many test assemblies in different directories, the actual mechanism whereby the instrumented code is executed is immaterial.  It doesn't even matter if an instrumented assembly is invoked from many separate OS processes; each instance will log coverage separately, to be gathered together at the end.

You don't even need to start the application using the runner mode; if you instrument using the `--save` parameter, you can run the e2e tests as normal, then use `altcover runner --collect` to gather up the data after everything has run -- which is effectively what the `dotnet test` integration MSBuild targets do, under the covers.

**Comment by nripendra** [comment]
Thanks! for the reply. It did work for me.
