### ISSUE TITLE
Crap score after upgrading

### ISSUE THREAD

**Issue by cartsp** [SteveGilham/altcover#97]
The following code with 1 test covering it:

```c#
        private async Task<bool> CheckFolderExists(string folder)
        {
            var spCredscontent = new StringContent(JsonConvert.SerializeObject(_sharePointCredentials), Encoding.UTF8, "application/json");
            try
            {
                using var response = await _client.PostAsync($"{_sharePointServiceEndpoints.SharepointWebserviceUrl}{_sharePointServiceEndpoints.CreateFolder}?folderToCreate={folder}&uploadedBy={User}", spCredscontent);

                return await IsResponseSuccessfulAsync(response);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error while checking {folder} exists in the JMS SharePoint.", ex);
                return false;
            }
        }
```
Reports a crap score of 15.38 on version v7.1.782 but 0 on 6.8.761.  Other sections of code have increased massively, this was just a method that was more copyable.  Not sure which is right, the Cyclomatic complexity is calculated at 9.

**Comment by SteveGilham** [comment]
Can you share the related section of the XML report?  Note that being an `async` method, the logic part of quoted code will reside in a compiler generated `MoveNext()` method and appear as such in the XML report, so the methods of interest are going to be named like `[ClassName]/&lt;CheckFolderExists&gt;d__0::[Something]` as well as the headline  `[ClassName::CheckFolderExists` .

In the case of a  method with cyclomatic complexity of 9, a 15.38 CRAP score works backwards to a coverage fraction of about 0.43 (about 3/7), which would look plausible for a single test.  A zero score is invalid,  the CRAP score being greater than or equal to the cyclomatic complexity of the method, which itself is always greater than or equal to 1

There have been a few fixes in this area at v 7.0, 7.1 -- from the release notes
* [BUGFIX] Compute CRAP score for unvisited methods too (and add it to the higher level summary items)
* [BUGFIX] Set the `visited` attribute and CRAP score accordingly for methods with no sequence points, if the method is recorded as having been visited at all.

The first of these would have the effect of taking any zero scores to higher values.

**Comment by cartsp** [comment]
Thanks Steve for the comprehensive answer.  I will try get the section from the XML report and paste it here.  Although I think you have answered the question, if 0 is an invalid score then I suspect one of the bug fixes you mentioned may be the reason.

That does leave me wondering now how that method has a cyclomatic complexity of 9, when it does not have any branching/looping aside from a single try catch.

**Comment by cartsp** [comment]
'''XML
<FullName>Infrastructure.Repositories.SharePointRepository.SharePointRepository/&lt;CheckFolderExists&gt;d__15</FullName>
          <Methods>
            <Method visited="false" cyclomaticComplexity="9" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false" crapScore="0">
              <Summary numSequencePoints="7" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="9" minCyclomaticComplexity="9" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="1" minCrapScore="0" maxCrapScore="0" />
              <MetadataToken>100663493</MetadataToken>
              <Name>System.Void Infrastructure.Repositories.SharePointRepository.SharePointRepository/&lt;CheckFolderExists&gt;d__15::MoveNext()</Name>
              <FileRef uid="488" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="202" ordinal="0" offset="18" sl="197" sc="13" el="197" ec="140" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="201" ordinal="1" offset="59" sl="200" sc="17" el="200" ec="220" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="200" ordinal="2" offset="247" sl="202" sc="17" el="202" ec="66" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="199" ordinal="3" offset="373" sl="204" sc="13" el="204" ec="33" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="198" ordinal="4" offset="375" sl="206" sc="17" el="206" ec="102" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="197" ordinal="5" offset="418" sl="207" sc="17" el="207" ec="30" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="196" ordinal="6" offset="447" sl="209" sc="9" el="209" ec="10" bec="0" bev="0" fileid="488" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint xsi:type="SequencePoint" vc="0" uspid="202" ordinal="0" offset="18" sl="197" sc="13" el="197" ec="140" bec="0" bev="0" fileid="488" />
            </Method>
            <Method visited="false" cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false" crapScore="0">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" minCrapScore="0" maxCrapScore="0" />
              <MetadataToken>100663494</MetadataToken>
              <Name>System.Void Infrastructure.Repositories.SharePointRepository.SharePointRepository/&lt;CheckFolderExists&gt;d__15::SetStateMachine(System.Runtime.CompilerServices.IAsyncStateMachine)</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="100663494" ordinal="0" offset="0" />
            </Method>
          </Methods>
        </Class>
'''

**Comment by cartsp** [comment]
```xml
          <Summary numSequencePoints="7" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="9" minCyclomaticComplexity="1" visitedClasses="0" numClasses="1" visitedMethods="0" numMethods="1" minCrapScore="90" maxCrapScore="90" />
          <FullName>Infrastructure.Repositories.SharePointRepository.SharePointRepository/&lt;CheckFolderExists&gt;d__15</FullName>
          <Methods>
            <Method visited="false" cyclomaticComplexity="9" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false" crapScore="90">
              <Summary numSequencePoints="7" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="9" minCyclomaticComplexity="9" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="1" minCrapScore="90" maxCrapScore="90" />
              <MetadataToken>100663493</MetadataToken>
              <Name>System.Void Infrastructure.Repositories.SharePointRepository.SharePointRepository/&lt;CheckFolderExists&gt;d__15::MoveNext()</Name>
              <FileRef uid="488" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="203" ordinal="0" offset="18" sl="197" sc="13" el="197" ec="140" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="202" ordinal="1" offset="59" sl="200" sc="17" el="200" ec="220" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="201" ordinal="2" offset="247" sl="202" sc="17" el="202" ec="66" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="200" ordinal="3" offset="373" sl="204" sc="13" el="204" ec="33" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="199" ordinal="4" offset="375" sl="206" sc="17" el="206" ec="102" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="198" ordinal="5" offset="418" sl="207" sc="17" el="207" ec="30" bec="0" bev="0" fileid="488" />
                <SequencePoint vc="0" uspid="197" ordinal="6" offset="447" sl="209" sc="9" el="209" ec="10" bec="0" bev="0" fileid="488" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint xsi:type="SequencePoint" vc="0" uspid="203" ordinal="0" offset="18" sl="197" sc="13" el="197" ec="140" bec="0" bev="0" fileid="488" />
            </Method>
            <Method visited="false" cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false" crapScore="2">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" minCrapScore="2" maxCrapScore="2" />
              <MetadataToken>100663494</MetadataToken>
              <Name>System.Void Infrastructure.Repositories.SharePointRepository.SharePointRepository/&lt;CheckFolderExists&gt;d__15::SetStateMachine(System.Runtime.CompilerServices.IAsyncStateMachine)</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="100663494" ordinal="0" offset="0" />
            </Method>
          </Methods>
        </Class>
```
Is from the v7.1.782 version

**Comment by cartsp** [comment]
I just realised this is the unit test report which does not run on the method, it is the integration test that hits it... The output from the merged report in report generator look like:

![image](https://user-images.githubusercontent.com/1150226/96228311-56714000-0f8d-11eb-97dd-8dc9f513df69.png)

**Comment by cartsp** [comment]
```xml
        <Class>
          <Summary numSequencePoints="7" visitedSequencePoints="4" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="57.14" branchCoverage="0" maxCyclomaticComplexity="9" minCyclomaticComplexity="1" visitedClasses="1" numClasses="1" visitedMethods="1" numMethods="1" minCrapScore="15.38" maxCrapScore="15.38" />
          <FullName>Infrastructure.Repositories.SharePointRepository.SharePointRepository/&lt;CheckFolderExists&gt;d__15</FullName>
          <Methods>
            <Method visited="true" cyclomaticComplexity="9" nPathComplexity="0" sequenceCoverage="57.14" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false" crapScore="15.38">
              <Summary numSequencePoints="7" visitedSequencePoints="4" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="57.14" branchCoverage="0" maxCyclomaticComplexity="9" minCyclomaticComplexity="9" visitedClasses="0" numClasses="0" visitedMethods="1" numMethods="1" minCrapScore="15.38" maxCrapScore="15.38" />
              <MetadataToken>100663493</MetadataToken>
              <Name>System.Void Infrastructure.Repositories.SharePointRepository.SharePointRepository/&lt;CheckFolderExists&gt;d__15::MoveNext()</Name>
              <FileRef uid="493" />
              <SequencePoints>
                <SequencePoint vc="1" uspid="203" ordinal="0" offset="18" sl="197" sc="13" el="197" ec="140" bec="0" bev="0" fileid="493" />
                <SequencePoint vc="1" uspid="202" ordinal="1" offset="59" sl="200" sc="17" el="200" ec="220" bec="0" bev="0" fileid="493" />
                <SequencePoint vc="1" uspid="201" ordinal="2" offset="247" sl="202" sc="17" el="202" ec="66" bec="0" bev="0" fileid="493" />
                <SequencePoint vc="0" uspid="200" ordinal="3" offset="373" sl="204" sc="13" el="204" ec="33" bec="0" bev="0" fileid="493" />
                <SequencePoint vc="0" uspid="199" ordinal="4" offset="375" sl="206" sc="17" el="206" ec="102" bec="0" bev="0" fileid="493" />
                <SequencePoint vc="0" uspid="198" ordinal="5" offset="418" sl="207" sc="17" el="207" ec="30" bec="0" bev="0" fileid="493" />
                <SequencePoint vc="1" uspid="197" ordinal="6" offset="447" sl="209" sc="9" el="209" ec="10" bec="0" bev="0" fileid="493" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint xsi:type="SequencePoint" vc="1" uspid="203" ordinal="0" offset="18" sl="197" sc="13" el="197" ec="140" bec="0" bev="0" fileid="493" />
            </Method>
            <Method visited="false" cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false" crapScore="2">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" minCrapScore="2" maxCrapScore="2" />
              <MetadataToken>100663494</MetadataToken>
              <Name>System.Void Infrastructure.Repositories.SharePointRepository.SharePointRepository/&lt;CheckFolderExists&gt;d__15::SetStateMachine(System.Runtime.CompilerServices.IAsyncStateMachine)</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="100663494" ordinal="0" offset="0" />
            </Method>
          </Methods>
        </Class>
```
Is from the v7.1.782 version of the integration tests

**Comment by SteveGilham** [comment]
That's interesting.  Taking an essentially identical dummy method
```
    public async Task<bool> CheckFolderExists(string folder)
    {
      try
      {
        using var response = await client.PostAsync(String.Empty, null);

        return await IsResponseSuccessfulAsync(response);
      }
      catch (Exception e)
      {
        return false;
      }
    }
```
and running `AltCover.exe -i [path to debug output]` I get (for the raw report, no coverage gathered)
```
            <Method visited="false" cyclomaticComplexity="9" nPathComplexity="8" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false" crapScore="0">
              <Summary numSequencePoints="8" visitedSequencePoints="0" numBranchPoints="7" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="9" minCyclomaticComplexity="9" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="1" minCrapScore="0" maxCrapScore="0" />
              <MetadataToken>100663312</MetadataToken>
              <Name>System.Void ClassLibrary1.Class2/&lt;CheckFolderExists&gt;d__1::MoveNext()</Name>
              <FileRef uid="1" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="16" ordinal="0" offset="15" sl="56" sc="5" el="56" ec="6" bec="4" bev="0" fileid="1" />
                <SequencePoint vc="0" uspid="15" ordinal="1" offset="35" sl="58" sc="7" el="58" ec="8" bec="0" bev="0" fileid="1" />
                <SequencePoint vc="0" uspid="14" ordinal="2" offset="36" sl="59" sc="9" el="59" ec="73" bec="2" bev="0" fileid="1" />
                <SequencePoint vc="0" uspid="13" ordinal="3" offset="181" sl="61" sc="9" el="61" ec="58" bec="0" bev="0" fileid="1" />
                <SequencePoint vc="0" uspid="12" ordinal="4" offset="330" sl="63" sc="7" el="63" ec="26" bec="0" bev="0" fileid="1" />
                <SequencePoint vc="0" uspid="11" ordinal="5" offset="340" sl="64" sc="7" el="64" ec="8" bec="0" bev="0" fileid="1" />
                <SequencePoint vc="0" uspid="10" ordinal="6" offset="341" sl="65" sc="9" el="65" ec="22" bec="0" bev="0" fileid="1" />
                <SequencePoint vc="0" uspid="9" ordinal="7" offset="371" sl="67" sc="5" el="67" ec="6" bec="0" bev="0" fileid="1" />
              </SequencePoints>
              <BranchPoints>
                <BranchPoint vc="0" uspid="0" ordinal="0" offset="18" sl="56" path="0" offsetchain="20" offsetend="22" fileid="1" />
                <BranchPoint vc="0" uspid="1" ordinal="1" offset="18" sl="56" path="1" offsetchain="28" offsetend="112" fileid="1" />
                <BranchPoint vc="0" uspid="2" ordinal="2" offset="24" sl="56" path="0" offsetchain="26" offsetend="35" fileid="1" />
                <BranchPoint vc="0" uspid="3" ordinal="3" offset="24" sl="56" path="1" offsetchain="30" offsetend="172" fileid="1" />
                <BranchPoint vc="0" uspid="4" ordinal="4" offset="175" sl="59" path="0" offsetchain="177" offsetend="181" fileid="1" />
                <BranchPoint vc="0" uspid="5" ordinal="5" offset="175" sl="59" path="1" offsetchain="179" offsetend="254" fileid="1" />
              </BranchPoints>
              <MethodPoint />
            </Method>
```
Are you using the `--linecover` option to the command line (to suppress recording branch coverage)?

**Comment by cartsp** [comment]
I use the following which is the same thing I guess:

dotnet test --configuration release "/p:AltCover=true" "/p:AltCoverForce=true" "/p:AltCoverLineCover=true" "/p:AltCoverAttributeFilter=ExcludeFromCodeCoverage"

**Comment by SteveGilham** [comment]
Methods with `async`/`await` involve a compiler generated state machine that weaves in branches from one user-level statement to another; the compiled code looks like this (where I've annotated as comments where the user level code matches up to the instruction offsets)
```
// ClassLibrary1.Class2.<CheckFolderExists>d__1
using System;
using System.Net.Http;
using System.Runtime.CompilerServices;

private void MoveNext()
{
	int num = <>1__state;
	bool result;
	try // try 
	{
		if ((uint)num > 1u)
		{
		}
		try
		{
			TaskAwaiter<HttpResponseMessage> awaiter;
			if (num != 0)
			{
				if (num == 1)
				{
					goto IL_00ac;
				}
				awaiter = <>4__this.client.PostAsync(string.Empty, null).GetAwaiter(); // { using var response = await client.PostAsync(String.Empty, null);
				if (!awaiter.IsCompleted)
				{
					num = (<>1__state = 0);
					<>u__1 = awaiter;
					<CheckFolderExists>d__1 stateMachine = this;
					<>t__builder.AwaitUnsafeOnCompleted(ref awaiter, ref stateMachine);
					return;
				}
			}
			else
			{
				awaiter = <>u__1;
				<>u__1 = default(TaskAwaiter<HttpResponseMessage>);
				num = (<>1__state = -1);
			}
			<>s__2 = awaiter.GetResult();
			<response>5__1 = <>s__2;
			<>s__2 = null;
			goto IL_00ac;
			IL_00ac:
			try
			{
				TaskAwaiter<bool> awaiter2;
				if (num != 1)
				{
					awaiter2 = <>4__this.IsResponseSuccessfulAsync(<response>5__1).GetAwaiter(); // return await IsResponseSuccessfulAsync(response);
					if (!awaiter2.IsCompleted)
					{
						num = (<>1__state = 1);
						<>u__2 = awaiter2;
						<CheckFolderExists>d__1 stateMachine = this;
						<>t__builder.AwaitUnsafeOnCompleted(ref awaiter2, ref stateMachine);
						return;
					}
				}
				else
				{
					awaiter2 = <>u__2;
					<>u__2 = default(TaskAwaiter<bool>);
					num = (<>1__state = -1);
				}
				<>s__3 = awaiter2.GetResult();
				result = <>s__3;
			}
			finally
			{
				if (num < 0 && <response>5__1 != null)
				{
					((IDisposable)<response>5__1).Dispose();
				}
			}
		}
		catch (Exception ex) // } catch (Exception e)
		{
			Exception ex2 = <e>5__4 = ex;  // { return false;
			result = false;
		}
	}
	catch (Exception exception)
	{
		<>1__state = -2;
		<>t__builder.SetException(exception);
		return;
	}
	<>1__state = -2; // }
	<>t__builder.SetResult(result);
}
```

**Comment by cartsp** [comment]
Thanks again for a great explanation, I had suspected it might be the generated state machines, good to know, but I suppose as this is compiler generated code it isn't something other developers working on the code will ever get to see and won't effect the maintainability/complexity of the code? 
I would not consider the method I have pasted very complex, is there any way to ignore the generated state machines from the reporting of the cyclomatic complexity/crap scores or is this wishful thinking?

**Comment by SteveGilham** [comment]
To get the actual user visible complexity requires looking at and tokenizing the actual source code to count the branching constructs actually present then -- [see e.g. here](https://www.ndepend.com/docs/code-metrics#CC) -- and so is necessarily language specific (and in truth out of scope for a language agnostic tool).  The measure present here is for compatibility with the original OpenCover tool, and, like its prototype, at least as of 3 years ago, [computes values for the IL it's given](https://www.ndepend.com/docs/code-metrics#ILCC).

For C# code, getting the user visible complexity is something a Roslyn based tool could accomplish, but a quick search only turns up [the CA1502 FxCop analyzer](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md#ca1502-avoid-excessive-complexity) that only flags methods with values of 25+ as a warning.    This would be a separate project (even if what it did was take an OpenCover format report, find the C# code, and repack the coverage and complexity data to show only the user-visible functions and branches).

For more directly test coverage purposes, i.e. the purpose of this tool, these sorts of branches lead to false positives for missing tests in logic that is not directly testable (in this case, the branch being conditional on "did we complete the async operation already?").  AltCover already contains the simple heuristic  that branches that start and end inside a user-level statement are likely to be the compiler being clever (e.g. caching lambdas or optimizing switch statements), so to ignore them when computing branch points.

Unfortunately, while I would love to just exclude them from the counts, the added branches in the `async`/`await` IL don't appear to have any such obvious local fingerprints to distinguish them from ones that may be present in the original source code.  However, prompted by this issue, I've looked back at the (generally moribund) [OpenCover project](https://github.com/OpenCover/opencover), and it looks like that has, since I last checked, abandoned its purist approach of reporting every single branch and has made some effort in this direction.

For that reason, I shall mark this as an enhancement request pending further investigation.

**Comment by cartsp** [comment]
Thanks Steve, I cannot imagine it is trivial at all. 

 I appreciate the time you have taken to answer everything so comprehensively.  Thanks for everything you have done with this, its been a massive help keeping track of our code.

**Comment by SteveGilham** [comment]
You're very welcome.

**Comment by SteveGilham** [comment]
I wrote
> the added branches in the `async`/`await` IL don't appear to have any such obvious local fingerprints to distinguish them from ones that may be present in the original source code
but on further inspection there turned out to be at least one frequent fingerprint (an Ldloc_0 instruction at a generated sequence point immediately before the branch instruction)

Release v7.3.805 uses this to recognise and discard such generated branches, which should complete the resolution of this issue.

**Comment by cartsp** [comment]
I kept meaning to write to say thanks Steve, this has been so useful, much appreciated!
