### ISSUE TITLE
Get timing data?

### ISSUE THREAD

**Issue by ffMathy** [SteveGilham/altcover#99]
Is it possible to get test durations of each test as part of the coverage?

**Comment by SteveGilham** [comment]
Currently. no.  It would be simple to record entry and exit times while performing the call monitoring though.  I'll have to think how best to represent those in the XML.

**Comment by ffMathy** [comment]
It could be context based. So if the call context is set to the test attribute, it could time it based on the tracked methods.

That'd be perfect for my scenario. 

And also, can I just say THANK YOU for tirelessly maintaining this project. It's way better than the competition. 

Is there a way I can donate?

**Comment by SteveGilham** [comment]
In the 7.1.795 release, the `<TrackedMethod />` records gain an optional `entry` and `exit` attribute, each being a semicolon-separated list of the entry or exit times (as decimal integer `DateTime.UtcNow.Ticks` values).  In the case where a list is empty, the attribute is not shown (e.g. method never executed, or, in the case of pause/resume data collection, where the entry or exit falls inside a paused period). Is there anything else needed to resolve this issue?

As to the other matter -- when I picked up this project again after I retired from coding for pay, from where it had gathered dust for many years, it was with the intent of keeping my hand in, coding-wise.  The original target was simply to take what had started as an `NCover` 1.5 emulator and make feature parity with `OpenCover`, while addressing a few matters of taste (e.g. around which compiler generated branches were worth reporting), to be a tool that I would then use in my other projects.  I'd not anticipated that not being tied to the .Net framework profiling APIs would fit so neatly into the new .net core, but that, and adding "and also `coverlet`", became a convenient, if unanticipated, set of stretch goals.

Being an old-fashioned guy, I don't have an obvious way of receiving direct donations, but I do have an amazon.co.uk wishlist and could also take vouchers -- we'd just want to arrange a less public channel for communication for the latter.

**Comment by ffMathy** [comment]
Thank you! Yes, the issue is resolved now. Amazing!

As for donations, do you have Skype? My username is mathiaslylo there.

**Comment by SteveGilham** [comment]
Sorry about the delay -- getting everything building everywhere with the net5 SDK was a bit gnarlier than I had expected.  I'd thought "I'll just get this finished, and then respond", so I've started a private conversation on Skype.

I may be AFK from time to time, but texting is asynchronous anyway.

**Comment by ffMathy** [comment]
Ah, I see you added me already. I accepted your request.

Great to hear that .NET 5 is up and running too!

By the way, here's what your product has allowed me to create!
https://github.com/pruner/cli

It runs in a "watch" mode and then runs your tests as you change your code, but only the affected tests that ran through that code.

I'm working on making it compatible with build servers too. Imagine only having to run 3 tests instead of 1000!

Also, it works with the Coverage Gutters extension for Visual Studio Code to provide live coverage feedback. You can instantly know if you have broken something.
